# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui\dialog_tool_analysis.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog_analysis(object):
    def setupUi(self, Dialog_analysis):
        Dialog_analysis.setObjectName("Dialog_analysis")
        Dialog_analysis.resize(1008, 1008)
        Dialog_analysis.setStyleSheet("QWidget{\n"
"    background-color: rgb(67, 67, 67);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QScrollArea{\n"
"    border: 0px;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_analysis)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(Dialog_analysis)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 973, 1079))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setFlat(True)
        self.groupBox.setCheckable(False)
        self.groupBox.setChecked(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_analysis_nlp = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_analysis_nlp.setFlat(False)
        self.groupBox_analysis_nlp.setCheckable(True)
        self.groupBox_analysis_nlp.setChecked(False)
        self.groupBox_analysis_nlp.setObjectName("groupBox_analysis_nlp")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.groupBox_analysis_nlp)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.verticalLayout_3.addWidget(self.groupBox_analysis_nlp)
        self.groupBox_analysis_convex_hull = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_analysis_convex_hull.setFlat(False)
        self.groupBox_analysis_convex_hull.setCheckable(True)
        self.groupBox_analysis_convex_hull.setChecked(False)
        self.groupBox_analysis_convex_hull.setObjectName("groupBox_analysis_convex_hull")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.groupBox_analysis_convex_hull)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_3.addWidget(self.groupBox_analysis_convex_hull)
        self.groupBox_analysis_quality_control = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_analysis_quality_control.setFlat(True)
        self.groupBox_analysis_quality_control.setCheckable(True)
        self.groupBox_analysis_quality_control.setChecked(False)
        self.groupBox_analysis_quality_control.setObjectName("groupBox_analysis_quality_control")
        self.verticalLayout_3.addWidget(self.groupBox_analysis_quality_control)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setChecked(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_analysis_dbscan = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_analysis_dbscan.setFlat(False)
        self.groupBox_analysis_dbscan.setCheckable(True)
        self.groupBox_analysis_dbscan.setChecked(False)
        self.groupBox_analysis_dbscan.setObjectName("groupBox_analysis_dbscan")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_analysis_dbscan)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.line_2 = QtWidgets.QFrame(self.groupBox_analysis_dbscan)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_4.addWidget(self.line_2, 0, 6, 2, 2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 9, 2, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_analysis_dbscan)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 0, 1, 1, 1)
        self.spinBox_analysis_dbscan_eps = QtWidgets.QSpinBox(self.groupBox_analysis_dbscan)
        self.spinBox_analysis_dbscan_eps.setMinimum(1)
        self.spinBox_analysis_dbscan_eps.setMaximum(20000)
        self.spinBox_analysis_dbscan_eps.setSingleStep(10)
        self.spinBox_analysis_dbscan_eps.setProperty("value", 100)
        self.spinBox_analysis_dbscan_eps.setObjectName("spinBox_analysis_dbscan_eps")
        self.gridLayout_4.addWidget(self.spinBox_analysis_dbscan_eps, 0, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_analysis_dbscan)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 1, 1, 1, 1)
        self.spinBox_analysis_dbscan_minn = QtWidgets.QSpinBox(self.groupBox_analysis_dbscan)
        self.spinBox_analysis_dbscan_minn.setMinimum(1)
        self.spinBox_analysis_dbscan_minn.setMaximum(1000)
        self.spinBox_analysis_dbscan_minn.setProperty("value", 3)
        self.spinBox_analysis_dbscan_minn.setObjectName("spinBox_analysis_dbscan_minn")
        self.gridLayout_4.addWidget(self.spinBox_analysis_dbscan_minn, 1, 3, 1, 1)
        self.checkBox_analysis_dbscan_save_all = QtWidgets.QCheckBox(self.groupBox_analysis_dbscan)
        self.checkBox_analysis_dbscan_save_all.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_analysis_dbscan_save_all.setObjectName("checkBox_analysis_dbscan_save_all")
        self.gridLayout_4.addWidget(self.checkBox_analysis_dbscan_save_all, 0, 11, 1, 1)
        self.checkBox_analysis_dbscan_export_pdb = QtWidgets.QCheckBox(self.groupBox_analysis_dbscan)
        self.checkBox_analysis_dbscan_export_pdb.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_analysis_dbscan_export_pdb.setObjectName("checkBox_analysis_dbscan_export_pdb")
        self.gridLayout_4.addWidget(self.checkBox_analysis_dbscan_export_pdb, 1, 11, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBox_analysis_dbscan)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_4.setFlat(True)
        self.groupBox_4.setCheckable(False)
        self.groupBox_4.setChecked(False)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_analysis_internalization_surface = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_analysis_internalization_surface.setFlat(False)
        self.groupBox_analysis_internalization_surface.setCheckable(True)
        self.groupBox_analysis_internalization_surface.setChecked(False)
        self.groupBox_analysis_internalization_surface.setObjectName("groupBox_analysis_internalization_surface")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_analysis_internalization_surface)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.line_3 = QtWidgets.QFrame(self.groupBox_analysis_internalization_surface)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_5.addWidget(self.line_3, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 0, 6, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_analysis_internalization_surface)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 0, 3, 1, 1)
        self.spinBox_analysis_internalization_surface_treshold = QtWidgets.QSpinBox(self.groupBox_analysis_internalization_surface)
        self.spinBox_analysis_internalization_surface_treshold.setMaximum(10000)
        self.spinBox_analysis_internalization_surface_treshold.setSingleStep(10)
        self.spinBox_analysis_internalization_surface_treshold.setProperty("value", 100)
        self.spinBox_analysis_internalization_surface_treshold.setObjectName("spinBox_analysis_internalization_surface_treshold")
        self.gridLayout_5.addWidget(self.spinBox_analysis_internalization_surface_treshold, 0, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_analysis_internalization_surface)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 0, 0, 1, 1)
        self.comboBox_analysis_internalization_surface_channel_convex = QtWidgets.QComboBox(self.groupBox_analysis_internalization_surface)
        self.comboBox_analysis_internalization_surface_channel_convex.setObjectName("comboBox_analysis_internalization_surface_channel_convex")
        self.gridLayout_5.addWidget(self.comboBox_analysis_internalization_surface_channel_convex, 1, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_analysis_internalization_surface)
        self.label_15.setObjectName("label_15")
        self.gridLayout_5.addWidget(self.label_15, 1, 0, 1, 1)
        self.comboBox_analysis_internalization_surface_channel_distance = QtWidgets.QComboBox(self.groupBox_analysis_internalization_surface)
        self.comboBox_analysis_internalization_surface_channel_distance.setObjectName("comboBox_analysis_internalization_surface_channel_distance")
        self.gridLayout_5.addWidget(self.comboBox_analysis_internalization_surface_channel_distance, 0, 1, 1, 1)
        self.checkBox_analysis_internalization_surface_save_all = QtWidgets.QCheckBox(self.groupBox_analysis_internalization_surface)
        self.checkBox_analysis_internalization_surface_save_all.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_analysis_internalization_surface_save_all.setObjectName("checkBox_analysis_internalization_surface_save_all")
        self.gridLayout_5.addWidget(self.checkBox_analysis_internalization_surface_save_all, 0, 7, 1, 1)
        self.verticalLayout_7.addWidget(self.groupBox_analysis_internalization_surface)
        self.groupBox_analysis_internalization_dr = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_analysis_internalization_dr.setFlat(False)
        self.groupBox_analysis_internalization_dr.setCheckable(True)
        self.groupBox_analysis_internalization_dr.setChecked(False)
        self.groupBox_analysis_internalization_dr.setObjectName("groupBox_analysis_internalization_dr")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_analysis_internalization_dr)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.comboBox_analysis_internalization_dr_channel_distance = QtWidgets.QComboBox(self.groupBox_analysis_internalization_dr)
        self.comboBox_analysis_internalization_dr_channel_distance.setObjectName("comboBox_analysis_internalization_dr_channel_distance")
        self.gridLayout_7.addWidget(self.comboBox_analysis_internalization_dr_channel_distance, 0, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_analysis_internalization_dr)
        self.label_16.setObjectName("label_16")
        self.gridLayout_7.addWidget(self.label_16, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem2, 0, 2, 1, 1)
        self.checkBox_analysis_internalization_dr_save_all = QtWidgets.QCheckBox(self.groupBox_analysis_internalization_dr)
        self.checkBox_analysis_internalization_dr_save_all.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_analysis_internalization_dr_save_all.setObjectName("checkBox_analysis_internalization_dr_save_all")
        self.gridLayout_7.addWidget(self.checkBox_analysis_internalization_dr_save_all, 0, 3, 1, 1)
        self.verticalLayout_7.addWidget(self.groupBox_analysis_internalization_dr)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.groupBox_6 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_6.setFlat(True)
        self.groupBox_6.setCheckable(False)
        self.groupBox_6.setChecked(False)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.groupBox_analysis_euclidean_within = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox_analysis_euclidean_within.setFlat(False)
        self.groupBox_analysis_euclidean_within.setCheckable(True)
        self.groupBox_analysis_euclidean_within.setChecked(False)
        self.groupBox_analysis_euclidean_within.setObjectName("groupBox_analysis_euclidean_within")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_analysis_euclidean_within)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem3, 0, 0, 1, 1)
        self.checkBox_analysis_euclidean_within_save_all = QtWidgets.QCheckBox(self.groupBox_analysis_euclidean_within)
        self.checkBox_analysis_euclidean_within_save_all.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_analysis_euclidean_within_save_all.setObjectName("checkBox_analysis_euclidean_within_save_all")
        self.gridLayout_6.addWidget(self.checkBox_analysis_euclidean_within_save_all, 0, 1, 1, 1)
        self.verticalLayout_8.addWidget(self.groupBox_analysis_euclidean_within)
        self.groupBox_analysis_euclidean_between = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox_analysis_euclidean_between.setFlat(False)
        self.groupBox_analysis_euclidean_between.setCheckable(True)
        self.groupBox_analysis_euclidean_between.setChecked(False)
        self.groupBox_analysis_euclidean_between.setObjectName("groupBox_analysis_euclidean_between")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_analysis_euclidean_between)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox_analysis_euclidean_between)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.comboBox_analysis_euclidean_between_channel_minimum_dist = QtWidgets.QComboBox(self.groupBox_analysis_euclidean_between)
        self.comboBox_analysis_euclidean_between_channel_minimum_dist.setObjectName("comboBox_analysis_euclidean_between_channel_minimum_dist")
        self.gridLayout_3.addWidget(self.comboBox_analysis_euclidean_between_channel_minimum_dist, 0, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_analysis_euclidean_between)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 1, 0, 1, 1)
        self.comboBox_analysis_euclidean_between_channel_from = QtWidgets.QComboBox(self.groupBox_analysis_euclidean_between)
        self.comboBox_analysis_euclidean_between_channel_from.setObjectName("comboBox_analysis_euclidean_between_channel_from")
        self.gridLayout_3.addWidget(self.comboBox_analysis_euclidean_between_channel_from, 1, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_3)
        self.groupBox_analysis_euclidean_between_confocal = QtWidgets.QGroupBox(self.groupBox_analysis_euclidean_between)
        self.groupBox_analysis_euclidean_between_confocal.setFlat(True)
        self.groupBox_analysis_euclidean_between_confocal.setCheckable(True)
        self.groupBox_analysis_euclidean_between_confocal.setChecked(False)
        self.groupBox_analysis_euclidean_between_confocal.setObjectName("groupBox_analysis_euclidean_between_confocal")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_analysis_euclidean_between_confocal)
        self.formLayout.setObjectName("formLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboBox_analysis_euclidean_between_channel_from_confocal = QtWidgets.QComboBox(self.groupBox_analysis_euclidean_between_confocal)
        self.comboBox_analysis_euclidean_between_channel_from_confocal.setObjectName("comboBox_analysis_euclidean_between_channel_from_confocal")
        self.horizontalLayout_2.addWidget(self.comboBox_analysis_euclidean_between_channel_from_confocal)
        self.label_2 = QtWidgets.QLabel(self.groupBox_analysis_euclidean_between_confocal)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spinBox_analysis_euclidean_between_channel_peak_threshold = QtWidgets.QSpinBox(self.groupBox_analysis_euclidean_between_confocal)
        self.spinBox_analysis_euclidean_between_channel_peak_threshold.setMaximum(100)
        self.spinBox_analysis_euclidean_between_channel_peak_threshold.setProperty("value", 10)
        self.spinBox_analysis_euclidean_between_channel_peak_threshold.setObjectName("spinBox_analysis_euclidean_between_channel_peak_threshold")
        self.horizontalLayout_2.addWidget(self.spinBox_analysis_euclidean_between_channel_peak_threshold)
        self.label_23 = QtWidgets.QLabel(self.groupBox_analysis_euclidean_between_confocal)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_2.addWidget(self.label_23)
        self.spinBox_analysis_euclidean_between_channel_distance_threshold = QtWidgets.QSpinBox(self.groupBox_analysis_euclidean_between_confocal)
        self.spinBox_analysis_euclidean_between_channel_distance_threshold.setMinimum(1)
        self.spinBox_analysis_euclidean_between_channel_distance_threshold.setMaximum(1000)
        self.spinBox_analysis_euclidean_between_channel_distance_threshold.setSingleStep(10)
        self.spinBox_analysis_euclidean_between_channel_distance_threshold.setProperty("value", 100)
        self.spinBox_analysis_euclidean_between_channel_distance_threshold.setObjectName("spinBox_analysis_euclidean_between_channel_distance_threshold")
        self.horizontalLayout_2.addWidget(self.spinBox_analysis_euclidean_between_channel_distance_threshold)
        self.label_24 = QtWidgets.QLabel(self.groupBox_analysis_euclidean_between_confocal)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_2.addWidget(self.label_24)
        self.spinBox_analysis_euclidean_between_channel_pixel_threshold = QtWidgets.QSpinBox(self.groupBox_analysis_euclidean_between_confocal)
        self.spinBox_analysis_euclidean_between_channel_pixel_threshold.setMaximum(100)
        self.spinBox_analysis_euclidean_between_channel_pixel_threshold.setProperty("value", 20)
        self.spinBox_analysis_euclidean_between_channel_pixel_threshold.setObjectName("spinBox_analysis_euclidean_between_channel_pixel_threshold")
        self.horizontalLayout_2.addWidget(self.spinBox_analysis_euclidean_between_channel_pixel_threshold)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_2)
        self.horizontalLayout_3.addWidget(self.groupBox_analysis_euclidean_between_confocal)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.checkBox_analysis_euclidean_between_save_all = QtWidgets.QCheckBox(self.groupBox_analysis_euclidean_between)
        self.checkBox_analysis_euclidean_between_save_all.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_analysis_euclidean_between_save_all.setObjectName("checkBox_analysis_euclidean_between_save_all")
        self.horizontalLayout_3.addWidget(self.checkBox_analysis_euclidean_between_save_all)
        self.gridLayout_9.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.verticalLayout_8.addWidget(self.groupBox_analysis_euclidean_between)
        self.groupBox_analysis_euclidean_surface_between = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox_analysis_euclidean_surface_between.setFlat(False)
        self.groupBox_analysis_euclidean_surface_between.setCheckable(True)
        self.groupBox_analysis_euclidean_surface_between.setChecked(False)
        self.groupBox_analysis_euclidean_surface_between.setObjectName("groupBox_analysis_euclidean_surface_between")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_analysis_euclidean_surface_between)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_13 = QtWidgets.QLabel(self.groupBox_analysis_euclidean_surface_between)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 2, 0, 1, 1)
        self.comboBox_analysis_euclidean_surface_between_channel_reference = QtWidgets.QComboBox(self.groupBox_analysis_euclidean_surface_between)
        self.comboBox_analysis_euclidean_surface_between_channel_reference.setObjectName("comboBox_analysis_euclidean_surface_between_channel_reference")
        self.gridLayout_2.addWidget(self.comboBox_analysis_euclidean_surface_between_channel_reference, 1, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 0, 5, 1, 1)
        self.comboBox_analysis_euclidean_surface_between_channel_convex = QtWidgets.QComboBox(self.groupBox_analysis_euclidean_surface_between)
        self.comboBox_analysis_euclidean_surface_between_channel_convex.setObjectName("comboBox_analysis_euclidean_surface_between_channel_convex")
        self.gridLayout_2.addWidget(self.comboBox_analysis_euclidean_surface_between_channel_convex, 0, 1, 1, 1)
        self.comboBox_analysis_euclidean_surface_between_channel_distance = QtWidgets.QComboBox(self.groupBox_analysis_euclidean_surface_between)
        self.comboBox_analysis_euclidean_surface_between_channel_distance.setObjectName("comboBox_analysis_euclidean_surface_between_channel_distance")
        self.gridLayout_2.addWidget(self.comboBox_analysis_euclidean_surface_between_channel_distance, 2, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.groupBox_analysis_euclidean_surface_between)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 0, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_analysis_euclidean_surface_between)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 1, 0, 1, 1)
        self.spinBox_analysis_euclidean_surface_between_distance_limit = QtWidgets.QSpinBox(self.groupBox_analysis_euclidean_surface_between)
        self.spinBox_analysis_euclidean_surface_between_distance_limit.setMinimum(1)
        self.spinBox_analysis_euclidean_surface_between_distance_limit.setMaximum(1000)
        self.spinBox_analysis_euclidean_surface_between_distance_limit.setSingleStep(10)
        self.spinBox_analysis_euclidean_surface_between_distance_limit.setProperty("value", 100)
        self.spinBox_analysis_euclidean_surface_between_distance_limit.setObjectName("spinBox_analysis_euclidean_surface_between_distance_limit")
        self.gridLayout_2.addWidget(self.spinBox_analysis_euclidean_surface_between_distance_limit, 0, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_analysis_euclidean_surface_between)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_analysis_euclidean_surface_between)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 3, 1, 1)
        self.checkBox_analysis_euclidean_surface_between_save_all = QtWidgets.QCheckBox(self.groupBox_analysis_euclidean_surface_between)
        self.checkBox_analysis_euclidean_surface_between_save_all.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_analysis_euclidean_surface_between_save_all.setObjectName("checkBox_analysis_euclidean_surface_between_save_all")
        self.gridLayout_2.addWidget(self.checkBox_analysis_euclidean_surface_between_save_all, 0, 7, 1, 1)
        self.checkBox_analysis_euclidean_surface_between_export_pdb = QtWidgets.QCheckBox(self.groupBox_analysis_euclidean_surface_between)
        self.checkBox_analysis_euclidean_surface_between_export_pdb.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_analysis_euclidean_surface_between_export_pdb.setObjectName("checkBox_analysis_euclidean_surface_between_export_pdb")
        self.gridLayout_2.addWidget(self.checkBox_analysis_euclidean_surface_between_export_pdb, 1, 7, 1, 1)
        self.verticalLayout_8.addWidget(self.groupBox_analysis_euclidean_surface_between)
        self.verticalLayout_2.addWidget(self.groupBox_6)
        self.groupBox_13 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_13.setFlat(True)
        self.groupBox_13.setCheckable(False)
        self.groupBox_13.setChecked(False)
        self.groupBox_13.setObjectName("groupBox_13")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_13)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.groupBox_analysis_surface_density = QtWidgets.QGroupBox(self.groupBox_13)
        self.groupBox_analysis_surface_density.setFlat(False)
        self.groupBox_analysis_surface_density.setCheckable(True)
        self.groupBox_analysis_surface_density.setChecked(False)
        self.groupBox_analysis_surface_density.setObjectName("groupBox_analysis_surface_density")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_analysis_surface_density)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox_analysis_surface_density_channel_convex = QtWidgets.QComboBox(self.groupBox_analysis_surface_density)
        self.comboBox_analysis_surface_density_channel_convex.setObjectName("comboBox_analysis_surface_density_channel_convex")
        self.gridLayout.addWidget(self.comboBox_analysis_surface_density_channel_convex, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_analysis_surface_density)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 0, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.groupBox_analysis_surface_density)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout.addWidget(self.line_6, 0, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_analysis_surface_density)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 1, 0, 1, 1)
        self.comboBox_analysis_surface_density_channel_density = QtWidgets.QComboBox(self.groupBox_analysis_surface_density)
        self.comboBox_analysis_surface_density_channel_density.setObjectName("comboBox_analysis_surface_density_channel_density")
        self.gridLayout.addWidget(self.comboBox_analysis_surface_density_channel_density, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_analysis_surface_density)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_analysis_surface_density)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 3, 1, 1)
        self.spinBox_analysis_surface_density_treshold = QtWidgets.QSpinBox(self.groupBox_analysis_surface_density)
        self.spinBox_analysis_surface_density_treshold.setMinimum(1)
        self.spinBox_analysis_surface_density_treshold.setMaximum(1000)
        self.spinBox_analysis_surface_density_treshold.setProperty("value", 80)
        self.spinBox_analysis_surface_density_treshold.setObjectName("spinBox_analysis_surface_density_treshold")
        self.gridLayout.addWidget(self.spinBox_analysis_surface_density_treshold, 1, 4, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 0, 9, 1, 1)
        self.doubleSpinBox_analysis_surface_density_density = QtWidgets.QDoubleSpinBox(self.groupBox_analysis_surface_density)
        self.doubleSpinBox_analysis_surface_density_density.setDecimals(0)
        self.doubleSpinBox_analysis_surface_density_density.setMinimum(1.0)
        self.doubleSpinBox_analysis_surface_density_density.setMaximum(100000.0)
        self.doubleSpinBox_analysis_surface_density_density.setSingleStep(100.0)
        self.doubleSpinBox_analysis_surface_density_density.setProperty("value", 800.0)
        self.doubleSpinBox_analysis_surface_density_density.setObjectName("doubleSpinBox_analysis_surface_density_density")
        self.gridLayout.addWidget(self.doubleSpinBox_analysis_surface_density_density, 0, 4, 1, 1)
        self.checkBox_analysis_surface_density_save_all = QtWidgets.QCheckBox(self.groupBox_analysis_surface_density)
        self.checkBox_analysis_surface_density_save_all.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_analysis_surface_density_save_all.setObjectName("checkBox_analysis_surface_density_save_all")
        self.gridLayout.addWidget(self.checkBox_analysis_surface_density_save_all, 0, 10, 1, 1)
        self.verticalLayout_11.addWidget(self.groupBox_analysis_surface_density)
        self.groupBox_analysis_surface_density_distribution = QtWidgets.QGroupBox(self.groupBox_13)
        self.groupBox_analysis_surface_density_distribution.setFlat(False)
        self.groupBox_analysis_surface_density_distribution.setCheckable(True)
        self.groupBox_analysis_surface_density_distribution.setChecked(False)
        self.groupBox_analysis_surface_density_distribution.setObjectName("groupBox_analysis_surface_density_distribution")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_analysis_surface_density_distribution)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.comboBox_analysis_surface_density_distribution_channel_convex = QtWidgets.QComboBox(self.groupBox_analysis_surface_density_distribution)
        self.comboBox_analysis_surface_density_distribution_channel_convex.setObjectName("comboBox_analysis_surface_density_distribution_channel_convex")
        self.gridLayout_8.addWidget(self.comboBox_analysis_surface_density_distribution_channel_convex, 0, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_analysis_surface_density_distribution)
        self.label_18.setObjectName("label_18")
        self.gridLayout_8.addWidget(self.label_18, 0, 0, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.groupBox_analysis_surface_density_distribution)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_8.addWidget(self.line_7, 0, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_analysis_surface_density_distribution)
        self.label_19.setObjectName("label_19")
        self.gridLayout_8.addWidget(self.label_19, 1, 0, 1, 1)
        self.comboBox_analysis_surface_density_distribution_channel_density = QtWidgets.QComboBox(self.groupBox_analysis_surface_density_distribution)
        self.comboBox_analysis_surface_density_distribution_channel_density.setObjectName("comboBox_analysis_surface_density_distribution_channel_density")
        self.gridLayout_8.addWidget(self.comboBox_analysis_surface_density_distribution_channel_density, 1, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_analysis_surface_density_distribution)
        self.label_20.setObjectName("label_20")
        self.gridLayout_8.addWidget(self.label_20, 0, 3, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_analysis_surface_density_distribution)
        self.label_21.setObjectName("label_21")
        self.gridLayout_8.addWidget(self.label_21, 1, 3, 1, 1)
        self.spinBox_analysis_surface_density_distribution_treshold = QtWidgets.QSpinBox(self.groupBox_analysis_surface_density_distribution)
        self.spinBox_analysis_surface_density_distribution_treshold.setMinimum(1)
        self.spinBox_analysis_surface_density_distribution_treshold.setMaximum(1000)
        self.spinBox_analysis_surface_density_distribution_treshold.setProperty("value", 80)
        self.spinBox_analysis_surface_density_distribution_treshold.setObjectName("spinBox_analysis_surface_density_distribution_treshold")
        self.gridLayout_8.addWidget(self.spinBox_analysis_surface_density_distribution_treshold, 1, 4, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem7, 0, 9, 1, 1)
        self.doubleSpinBox_analysis_surface_density_distribution_density = QtWidgets.QDoubleSpinBox(self.groupBox_analysis_surface_density_distribution)
        self.doubleSpinBox_analysis_surface_density_distribution_density.setDecimals(0)
        self.doubleSpinBox_analysis_surface_density_distribution_density.setMaximum(100000.0)
        self.doubleSpinBox_analysis_surface_density_distribution_density.setSingleStep(100.0)
        self.doubleSpinBox_analysis_surface_density_distribution_density.setProperty("value", 800.0)
        self.doubleSpinBox_analysis_surface_density_distribution_density.setObjectName("doubleSpinBox_analysis_surface_density_distribution_density")
        self.gridLayout_8.addWidget(self.doubleSpinBox_analysis_surface_density_distribution_density, 0, 4, 1, 1)
        self.comboBox_analysis_surface_density_distribution_channel_reference = QtWidgets.QComboBox(self.groupBox_analysis_surface_density_distribution)
        self.comboBox_analysis_surface_density_distribution_channel_reference.setObjectName("comboBox_analysis_surface_density_distribution_channel_reference")
        self.gridLayout_8.addWidget(self.comboBox_analysis_surface_density_distribution_channel_reference, 2, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox_analysis_surface_density_distribution)
        self.label_22.setObjectName("label_22")
        self.gridLayout_8.addWidget(self.label_22, 2, 0, 1, 1)
        self.checkBox_analysis_surface_density_distribution_save_all = QtWidgets.QCheckBox(self.groupBox_analysis_surface_density_distribution)
        self.checkBox_analysis_surface_density_distribution_save_all.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_analysis_surface_density_distribution_save_all.setObjectName("checkBox_analysis_surface_density_distribution_save_all")
        self.gridLayout_8.addWidget(self.checkBox_analysis_surface_density_distribution_save_all, 0, 10, 1, 1)
        self.verticalLayout_11.addWidget(self.groupBox_analysis_surface_density_distribution)
        self.verticalLayout_2.addWidget(self.groupBox_13)
        self.groupBox_15 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_15.setFlat(True)
        self.groupBox_15.setCheckable(False)
        self.groupBox_15.setChecked(False)
        self.groupBox_15.setObjectName("groupBox_15")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_15)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.groupBox_analysis_export_coords = QtWidgets.QGroupBox(self.groupBox_15)
        self.groupBox_analysis_export_coords.setFlat(False)
        self.groupBox_analysis_export_coords.setCheckable(True)
        self.groupBox_analysis_export_coords.setChecked(False)
        self.groupBox_analysis_export_coords.setObjectName("groupBox_analysis_export_coords")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_analysis_export_coords)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_12.addWidget(self.groupBox_analysis_export_coords)
        self.groupBox_analysis_export_pdb = QtWidgets.QGroupBox(self.groupBox_15)
        self.groupBox_analysis_export_pdb.setFlat(False)
        self.groupBox_analysis_export_pdb.setCheckable(True)
        self.groupBox_analysis_export_pdb.setChecked(False)
        self.groupBox_analysis_export_pdb.setObjectName("groupBox_analysis_export_pdb")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.groupBox_analysis_export_pdb)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.verticalLayout_12.addWidget(self.groupBox_analysis_export_pdb)
        self.checkBox_analysis_export_plots = QtWidgets.QGroupBox(self.groupBox_15)
        self.checkBox_analysis_export_plots.setFlat(True)
        self.checkBox_analysis_export_plots.setCheckable(True)
        self.checkBox_analysis_export_plots.setChecked(False)
        self.checkBox_analysis_export_plots.setObjectName("checkBox_analysis_export_plots")
        self.verticalLayout_12.addWidget(self.checkBox_analysis_export_plots)
        self.verticalLayout_2.addWidget(self.groupBox_15)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem8)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)
        self.pushButton_analysis_run = QtWidgets.QPushButton(Dialog_analysis)
        self.pushButton_analysis_run.setObjectName("pushButton_analysis_run")
        self.horizontalLayout.addWidget(self.pushButton_analysis_run)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog_analysis)
        QtCore.QMetaObject.connectSlotsByName(Dialog_analysis)

    def retranslateUi(self, Dialog_analysis):
        _translate = QtCore.QCoreApplication.translate
        Dialog_analysis.setWindowTitle(_translate("Dialog_analysis", "Analysis runner tool"))
        self.groupBox.setTitle(_translate("Dialog_analysis", "Measurements"))
        self.groupBox_analysis_nlp.setTitle(_translate("Dialog_analysis", "NLP per channel"))
        self.groupBox_analysis_convex_hull.setTitle(_translate("Dialog_analysis", "Convex hull volume"))
        self.groupBox_analysis_quality_control.setTitle(_translate("Dialog_analysis", "Quality control"))
        self.groupBox_2.setTitle(_translate("Dialog_analysis", "Cluster analysis"))
        self.groupBox_analysis_dbscan.setTitle(_translate("Dialog_analysis", "DBSCAN"))
        self.label_7.setText(_translate("Dialog_analysis", "Eps (nm)"))
        self.label_8.setText(_translate("Dialog_analysis", "MinN"))
        self.checkBox_analysis_dbscan_save_all.setText(_translate("Dialog_analysis", "Save all data"))
        self.checkBox_analysis_dbscan_export_pdb.setText(_translate("Dialog_analysis", "Export in .pdb"))
        self.groupBox_4.setTitle(_translate("Dialog_analysis", "Internalization"))
        self.groupBox_analysis_internalization_surface.setTitle(_translate("Dialog_analysis", "Distance from surface"))
        self.label_3.setText(_translate("Dialog_analysis", "Threshold (nm)"))
        self.label_4.setText(_translate("Dialog_analysis", "Internalization distance calculation channel"))
        self.label_15.setText(_translate("Dialog_analysis", "Convex hull maker channel"))
        self.checkBox_analysis_internalization_surface_save_all.setText(_translate("Dialog_analysis", "Save all data"))
        self.groupBox_analysis_internalization_dr.setTitle(_translate("Dialog_analysis", "Distance from center of mass"))
        self.label_16.setText(_translate("Dialog_analysis", "Internalization Distance calculation channel"))
        self.checkBox_analysis_internalization_dr_save_all.setText(_translate("Dialog_analysis", "Save all data"))
        self.groupBox_6.setTitle(_translate("Dialog_analysis", "Minimum distances"))
        self.groupBox_analysis_euclidean_within.setTitle(_translate("Dialog_analysis", "Euclidean, within channel"))
        self.checkBox_analysis_euclidean_within_save_all.setText(_translate("Dialog_analysis", "Save all data"))
        self.groupBox_analysis_euclidean_between.setTitle(_translate("Dialog_analysis", "Euclidean, between channels"))
        self.label_5.setText(_translate("Dialog_analysis", "Minimum distance of points of channel"))
        self.label_14.setText(_translate("Dialog_analysis", "From channel"))
        self.groupBox_analysis_euclidean_between_confocal.setTitle(_translate("Dialog_analysis", "Reference channel from confocal"))
        self.label_2.setText(_translate("Dialog_analysis", "Peak det.(%)"))
        self.label_23.setText(_translate("Dialog_analysis", "dist.(nm)"))
        self.label_24.setText(_translate("Dialog_analysis", "pix. int. (%)"))
        self.checkBox_analysis_euclidean_between_save_all.setText(_translate("Dialog_analysis", "Save all data"))
        self.groupBox_analysis_euclidean_surface_between.setTitle(_translate("Dialog_analysis", "Surface, between channels"))
        self.label_13.setText(_translate("Dialog_analysis", "Distance calculation channel"))
        self.label_12.setText(_translate("Dialog_analysis", "Reference hull maker channel"))
        self.label_6.setText(_translate("Dialog_analysis", "Convex hull maker channel"))
        self.label.setText(_translate("Dialog_analysis", "Distance limit from convex hull (nm)"))
        self.checkBox_analysis_euclidean_surface_between_save_all.setText(_translate("Dialog_analysis", "Save all data"))
        self.checkBox_analysis_euclidean_surface_between_export_pdb.setText(_translate("Dialog_analysis", "Export in .pdb"))
        self.groupBox_13.setTitle(_translate("Dialog_analysis", "Surface Density"))
        self.groupBox_analysis_surface_density.setTitle(_translate("Dialog_analysis", "Measure surface density"))
        self.label_11.setText(_translate("Dialog_analysis", "Convex hull maker channel"))
        self.label_17.setText(_translate("Dialog_analysis", "Density calculation channel"))
        self.label_9.setText(_translate("Dialog_analysis", "Sampling density (NLP/µm^2)"))
        self.label_10.setText(_translate("Dialog_analysis", "Density probe radius (nm)"))
        self.checkBox_analysis_surface_density_save_all.setText(_translate("Dialog_analysis", "Save all data"))
        self.groupBox_analysis_surface_density_distribution.setTitle(_translate("Dialog_analysis", "Measure surface density distribution relative to reference"))
        self.label_18.setText(_translate("Dialog_analysis", "Convex hull maker channel"))
        self.label_19.setText(_translate("Dialog_analysis", "Density calculation channel"))
        self.label_20.setText(_translate("Dialog_analysis", "Sampling density (NLP/µm^2)"))
        self.label_21.setText(_translate("Dialog_analysis", "Density probe radius [nm]"))
        self.label_22.setText(_translate("Dialog_analysis", "Reference channel"))
        self.checkBox_analysis_surface_density_distribution_save_all.setText(_translate("Dialog_analysis", "Save all data"))
        self.groupBox_15.setTitle(_translate("Dialog_analysis", "Export data"))
        self.groupBox_analysis_export_coords.setTitle(_translate("Dialog_analysis", "Export coordinates"))
        self.groupBox_analysis_export_pdb.setTitle(_translate("Dialog_analysis", "Export to .pdb"))
        self.checkBox_analysis_export_plots.setTitle(_translate("Dialog_analysis", "Display plots"))
        self.pushButton_analysis_run.setText(_translate("Dialog_analysis", "Run"))

