# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui\dialog_tool_lut.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog_lut(object):
    def setupUi(self, Dialog_lut):
        Dialog_lut.setObjectName("Dialog_lut")
        Dialog_lut.setWindowModality(QtCore.Qt.WindowModal)
        Dialog_lut.resize(874, 376)
        Dialog_lut.setStyleSheet("QWidget{\n"
"    background-color: rgb(67, 67, 67);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_lut)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Dialog_lut)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(300, 0))
        self.groupBox_3.setMaximumSize(QtCore.QSize(400, 16777215))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_4 = QtWidgets.QWidget(self.groupBox_3)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_3 = QtWidgets.QWidget(self.widget_4)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.comboBox_storm_channel_changer = QtWidgets.QComboBox(self.widget_3)
        self.comboBox_storm_channel_changer.setObjectName("comboBox_storm_channel_changer")
        self.horizontalLayout_3.addWidget(self.comboBox_storm_channel_changer)
        self.verticalLayout_6.addWidget(self.widget_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.widget_4)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.spinBox_storm_LUT_lower = QtWidgets.QSpinBox(self.widget_4)
        self.spinBox_storm_LUT_lower.setMaximum(100)
        self.spinBox_storm_LUT_lower.setObjectName("spinBox_storm_LUT_lower")
        self.horizontalLayout_5.addWidget(self.spinBox_storm_LUT_lower)
        self.label_2 = QtWidgets.QLabel(self.widget_4)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.spinBox_storm_LUT_upper = QtWidgets.QSpinBox(self.widget_4)
        self.spinBox_storm_LUT_upper.setMaximum(100)
        self.spinBox_storm_LUT_upper.setProperty("value", 100)
        self.spinBox_storm_LUT_upper.setObjectName("spinBox_storm_LUT_upper")
        self.horizontalLayout_5.addWidget(self.spinBox_storm_LUT_upper)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.widget_3.raise_()
        self.verticalLayout_3.addWidget(self.widget_4)
        self.verticalLayout_storm_lut = QtWidgets.QVBoxLayout()
        self.verticalLayout_storm_lut.setObjectName("verticalLayout_storm_lut")
        self.verticalLayout_3.addLayout(self.verticalLayout_storm_lut)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(300, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(400, 16777215))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_5 = QtWidgets.QWidget(self.groupBox_2)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_2 = QtWidgets.QWidget(self.widget_5)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboBox_confocal_channel_changer = QtWidgets.QComboBox(self.widget_2)
        self.comboBox_confocal_channel_changer.setObjectName("comboBox_confocal_channel_changer")
        self.horizontalLayout_2.addWidget(self.comboBox_confocal_channel_changer)
        self.verticalLayout_4.addWidget(self.widget_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.widget_5)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.spinBox_confocal_LUT_lower = QtWidgets.QSpinBox(self.widget_5)
        self.spinBox_confocal_LUT_lower.setMaximum(100)
        self.spinBox_confocal_LUT_lower.setObjectName("spinBox_confocal_LUT_lower")
        self.horizontalLayout_6.addWidget(self.spinBox_confocal_LUT_lower)
        self.label_4 = QtWidgets.QLabel(self.widget_5)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.spinBox_confocal_LUT_upper = QtWidgets.QSpinBox(self.widget_5)
        self.spinBox_confocal_LUT_upper.setMaximum(100)
        self.spinBox_confocal_LUT_upper.setProperty("value", 100)
        self.spinBox_confocal_LUT_upper.setObjectName("spinBox_confocal_LUT_upper")
        self.horizontalLayout_6.addWidget(self.spinBox_confocal_LUT_upper)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.widget_5)
        self.verticalLayout_confocal_lut = QtWidgets.QVBoxLayout()
        self.verticalLayout_confocal_lut.setObjectName("verticalLayout_confocal_lut")
        self.verticalLayout_2.addLayout(self.verticalLayout_confocal_lut)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.verticalLayout.addWidget(self.widget)
        self.layoutWidget = QtWidgets.QWidget(Dialog_lut)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.layoutWidget1 = QtWidgets.QWidget(Dialog_lut)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.layoutWidget2 = QtWidgets.QWidget(Dialog_lut)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")

        self.retranslateUi(Dialog_lut)
        QtCore.QMetaObject.connectSlotsByName(Dialog_lut)

    def retranslateUi(self, Dialog_lut):
        _translate = QtCore.QCoreApplication.translate
        Dialog_lut.setWindowTitle(_translate("Dialog_lut", "LUT settings tool"))
        self.groupBox_3.setTitle(_translate("Dialog_lut", "STORM LUT"))
        self.label.setText(_translate("Dialog_lut", "Lower threshold"))
        self.label_2.setText(_translate("Dialog_lut", "Upper threshold"))
        self.groupBox_2.setTitle(_translate("Dialog_lut", "Confocal LUT"))
        self.label_3.setText(_translate("Dialog_lut", "Lower threshold"))
        self.label_4.setText(_translate("Dialog_lut", "Upper threshold"))

