# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui\dialog_matrix_parameters.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog_Matrix_Parameters(object):
    def setupUi(self, Dialog_Matrix_Parameters):
        Dialog_Matrix_Parameters.setObjectName("Dialog_Matrix_Parameters")
        Dialog_Matrix_Parameters.setWindowModality(QtCore.Qt.WindowModal)
        Dialog_Matrix_Parameters.setEnabled(True)
        Dialog_Matrix_Parameters.resize(600, 390)
        font = QtGui.QFont()
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        Dialog_Matrix_Parameters.setFont(font)
        Dialog_Matrix_Parameters.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        Dialog_Matrix_Parameters.setStyleSheet("\n"
"QWidget{\n"
"    background-color: rgb(67, 67, 67);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:checked{\n"
"    background-color: rgb(7, 2, 148);\n"
"}\n"
"QPushButton{\n"
"    color: rgb(255, 170,0);\n"
"}")
        Dialog_Matrix_Parameters.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_Matrix_Parameters)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, 5, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(Dialog_Matrix_Parameters)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.line = QtWidgets.QFrame(Dialog_Matrix_Parameters)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.line_2 = QtWidgets.QFrame(Dialog_Matrix_Parameters)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(Dialog_Matrix_Parameters)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        spacerItem = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.center_x = QtWidgets.QDoubleSpinBox(Dialog_Matrix_Parameters)
        self.center_x.setMinimum(-100000.0)
        self.center_x.setMaximum(100000.0)
        self.center_x.setObjectName("center_x")
        self.horizontalLayout.addWidget(self.center_x)
        self.center_y = QtWidgets.QDoubleSpinBox(Dialog_Matrix_Parameters)
        self.center_y.setMinimum(-100000.0)
        self.center_y.setMaximum(100000.0)
        self.center_y.setObjectName("center_y")
        self.horizontalLayout.addWidget(self.center_y)
        self.center_z = QtWidgets.QDoubleSpinBox(Dialog_Matrix_Parameters)
        self.center_z.setMinimum(-100000.0)
        self.center_z.setMaximum(100000.0)
        self.center_z.setObjectName("center_z")
        self.horizontalLayout.addWidget(self.center_z)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Dialog_Matrix_Parameters)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.distance = QtWidgets.QDoubleSpinBox(Dialog_Matrix_Parameters)
        self.distance.setMaximum(100000000.0)
        self.distance.setObjectName("distance")
        self.horizontalLayout_2.addWidget(self.distance)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(Dialog_Matrix_Parameters)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.elevation = QtWidgets.QDoubleSpinBox(Dialog_Matrix_Parameters)
        self.elevation.setMinimum(-180.0)
        self.elevation.setMaximum(180.0)
        self.elevation.setObjectName("elevation")
        self.horizontalLayout_3.addWidget(self.elevation)
        self.formLayout_2.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(Dialog_Matrix_Parameters)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.fov = QtWidgets.QDoubleSpinBox(Dialog_Matrix_Parameters)
        self.fov.setMaximum(180.0)
        self.fov.setObjectName("fov")
        self.horizontalLayout_5.addWidget(self.fov)
        self.formLayout_2.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(Dialog_Matrix_Parameters)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.azimuth = QtWidgets.QDoubleSpinBox(Dialog_Matrix_Parameters)
        self.azimuth.setMinimum(-180.0)
        self.azimuth.setMaximum(180.0)
        self.azimuth.setObjectName("azimuth")
        self.horizontalLayout_6.addWidget(self.azimuth)
        self.formLayout_2.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(Dialog_Matrix_Parameters)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.from_sim_stack = QtWidgets.QSpinBox(Dialog_Matrix_Parameters)
        self.from_sim_stack.setObjectName("from_sim_stack")
        self.horizontalLayout_8.addWidget(self.from_sim_stack)
        self.to_sim_stack = QtWidgets.QSpinBox(Dialog_Matrix_Parameters)
        self.to_sim_stack.setObjectName("to_sim_stack")
        self.horizontalLayout_8.addWidget(self.to_sim_stack)
        self.formLayout_2.setLayout(6, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.formLayout_2.setLayout(7, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_7)
        self.pushButton_sim_3d = QtWidgets.QPushButton(Dialog_Matrix_Parameters)
        self.pushButton_sim_3d.setCheckable(True)
        self.pushButton_sim_3d.setObjectName("pushButton_sim_3d")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.pushButton_sim_3d)
        self.pushButton_dstorm_3d = QtWidgets.QPushButton(Dialog_Matrix_Parameters)
        self.pushButton_dstorm_3d.setCheckable(True)
        self.pushButton_dstorm_3d.setChecked(True)
        self.pushButton_dstorm_3d.setObjectName("pushButton_dstorm_3d")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.pushButton_dstorm_3d)
        self.pushButton_ortho = QtWidgets.QPushButton(Dialog_Matrix_Parameters)
        self.pushButton_ortho.setCheckable(False)
        self.pushButton_ortho.setObjectName("pushButton_ortho")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.pushButton_ortho)
        self.pushButton_alpha_shape = QtWidgets.QPushButton(Dialog_Matrix_Parameters)
        self.pushButton_alpha_shape.setCheckable(True)
        self.pushButton_alpha_shape.setObjectName("pushButton_alpha_shape")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.pushButton_alpha_shape)
        self.verticalLayout_3.addLayout(self.formLayout_2)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 5, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_info_registration = QtWidgets.QLabel(Dialog_Matrix_Parameters)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_info_registration.sizePolicy().hasHeightForWidth())
        self.label_info_registration.setSizePolicy(sizePolicy)
        self.label_info_registration.setObjectName("label_info_registration")
        self.horizontalLayout_4.addWidget(self.label_info_registration)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_Matrix_Parameters)
        self.buttonBox.setStyleSheet("QPushButton{\n"
"        color: rgb(255, 255,255);\n"
"}")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.RestoreDefaults)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_4.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Dialog_Matrix_Parameters)
        self.buttonBox.accepted.connect(Dialog_Matrix_Parameters.accept)
        self.buttonBox.rejected.connect(Dialog_Matrix_Parameters.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Matrix_Parameters)

    def retranslateUi(self, Dialog_Matrix_Parameters):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Matrix_Parameters.setWindowTitle(_translate("Dialog_Matrix_Parameters", "Dialog"))
        self.label.setText(_translate("Dialog_Matrix_Parameters", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#ffaa00;\">View Transform</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog_Matrix_Parameters", "Center(x,y,z)"))
        self.label_2.setText(_translate("Dialog_Matrix_Parameters", "Distance of camera from center"))
        self.label_4.setText(_translate("Dialog_Matrix_Parameters", "Horizontal field of view in degrees"))
        self.label_6.setText(_translate("Dialog_Matrix_Parameters", "Camera\'s angle of elevation in degrees"))
        self.label_5.setText(_translate("Dialog_Matrix_Parameters", "Camera\'s azimuthal angle in degrees "))
        self.label_7.setText(_translate("Dialog_Matrix_Parameters", "SIM stacks for 3D view"))
        self.pushButton_sim_3d.setText(_translate("Dialog_Matrix_Parameters", "SIM 3D"))
        self.pushButton_dstorm_3d.setText(_translate("Dialog_Matrix_Parameters", "dSTORM 3D"))
        self.pushButton_ortho.setText(_translate("Dialog_Matrix_Parameters", "Ortho all in plane"))
        self.pushButton_alpha_shape.setText(_translate("Dialog_Matrix_Parameters", "dSTORM alpha shape"))
        self.label_info_registration.setText(_translate("Dialog_Matrix_Parameters", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">-</span></p></body></html>"))

