# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui\dialog_scale.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog_scale(object):
    def setupUi(self, Dialog_scale):
        Dialog_scale.setObjectName("Dialog_scale")
        Dialog_scale.resize(330, 239)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog_scale.sizePolicy().hasHeightForWidth())
        Dialog_scale.setSizePolicy(sizePolicy)
        Dialog_scale.setMaximumSize(QtCore.QSize(640, 480))
        Dialog_scale.setStyleSheet("QWidget{\n"
"    background-color: rgb(67, 67, 67);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_scale)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_scale_world = QtWidgets.QPushButton(Dialog_scale)
        self.pushButton_scale_world.setObjectName("pushButton_scale_world")
        self.gridLayout.addWidget(self.pushButton_scale_world, 1, 0, 1, 1)
        self.pushButton_scale_pixel = QtWidgets.QPushButton(Dialog_scale)
        self.pushButton_scale_pixel.setObjectName("pushButton_scale_pixel")
        self.gridLayout.addWidget(self.pushButton_scale_pixel, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(Dialog_scale)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        self.pushButton_scale_noscale = QtWidgets.QPushButton(Dialog_scale)
        self.pushButton_scale_noscale.setObjectName("pushButton_scale_noscale")
        self.verticalLayout.addWidget(self.pushButton_scale_noscale)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(Dialog_scale)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(Dialog_scale)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.spinBox_size = QtWidgets.QSpinBox(Dialog_scale)
        self.spinBox_size.setMaximum(99999999)
        self.spinBox_size.setObjectName("spinBox_size")
        self.horizontalLayout.addWidget(self.spinBox_size)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(Dialog_scale)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.spinBox_width = QtWidgets.QSpinBox(Dialog_scale)
        self.spinBox_width.setMaximum(999999999)
        self.spinBox_width.setObjectName("spinBox_width")
        self.horizontalLayout_2.addWidget(self.spinBox_width)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(Dialog_scale)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.spinBox_X = QtWidgets.QSpinBox(Dialog_scale)
        self.spinBox_X.setMinimum(-99999999)
        self.spinBox_X.setMaximum(999999999)
        self.spinBox_X.setObjectName("spinBox_X")
        self.horizontalLayout_3.addWidget(self.spinBox_X)
        self.spinBox_Y = QtWidgets.QSpinBox(Dialog_scale)
        self.spinBox_Y.setMinimum(-99999999)
        self.spinBox_Y.setMaximum(9999999)
        self.spinBox_Y.setObjectName("spinBox_Y")
        self.horizontalLayout_3.addWidget(self.spinBox_Y)
        self.spinBox_Z = QtWidgets.QSpinBox(Dialog_scale)
        self.spinBox_Z.setMinimum(-99999999)
        self.spinBox_Z.setMaximum(99999999)
        self.spinBox_Z.setObjectName("spinBox_Z")
        self.horizontalLayout_3.addWidget(self.spinBox_Z)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 5, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.show_custom_scale = QtWidgets.QPushButton(Dialog_scale)
        self.show_custom_scale.setObjectName("show_custom_scale")
        self.horizontalLayout_4.addWidget(self.show_custom_scale)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Dialog_scale)
        QtCore.QMetaObject.connectSlotsByName(Dialog_scale)

    def retranslateUi(self, Dialog_scale):
        _translate = QtCore.QCoreApplication.translate
        Dialog_scale.setWindowTitle(_translate("Dialog_scale", "Show scale"))
        self.pushButton_scale_world.setText(_translate("Dialog_scale", "World"))
        self.pushButton_scale_pixel.setText(_translate("Dialog_scale", "Pixel"))
        self.label.setText(_translate("Dialog_scale", "Select coordinate system"))
        self.pushButton_scale_noscale.setText(_translate("Dialog_scale", "Hide"))
        self.label_2.setText(_translate("Dialog_scale", "Scale in lower left corner"))
        self.label_3.setText(_translate("Dialog_scale", "Size [nm]"))
        self.label_4.setText(_translate("Dialog_scale", "Width"))
        self.label_5.setText(_translate("Dialog_scale", "Position(x,y,z)"))
        self.show_custom_scale.setText(_translate("Dialog_scale", "Show/ Hide"))

