from PyQt5 import QtCore, QtGui, QtWidgets

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtCore.QCoreApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtCore.QCoreApplication.translate(context, text, disambig)

class Ui_Dialog_openSTORM(object):
    def setupUi(self, Dialog_openSTORM):
        Dialog_openSTORM.setObjectName("Dialog_openSTORM")
        Dialog_openSTORM.setWindowModality(QtCore.Qt.WindowModal)
        Dialog_openSTORM.resize(658, 123)
        Dialog_openSTORM.setStyleSheet("QWidget{\n"
"    background-color: rgb(67, 67, 67);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.formLayout = QtWidgets.QFormLayout(Dialog_openSTORM)
        self.formLayout.setObjectName("formLayout")
        self.widget = QtWidgets.QWidget(Dialog_openSTORM)
        self.widget.setObjectName("widget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.widget)
        #self.formLayout_2.setMargin(0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(300, 0))
        self.groupBox_3.setMaximumSize(QtCore.QSize(400, 16777215))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.listWidget_storm_input = QtWidgets.QListWidget(self.groupBox_3)
        self.listWidget_storm_input.setObjectName("listWidget_storm_input")
        self.gridLayout_3.addWidget(self.listWidget_storm_input, 1, 1, 1, 1)
        self.horizontalLayout_4.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(300, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(400, 16777215))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.listWidget_trans_matrix_input = QtWidgets.QListWidget(self.groupBox_2)
        self.listWidget_trans_matrix_input.setObjectName("listWidget_trans_matrix_input")
        self.gridLayout_4.addWidget(self.listWidget_trans_matrix_input, 0, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.groupBox_2)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_open_storm = QtWidgets.QPushButton(self.widget)
        self.pushButton_open_storm.setObjectName("OpenSTORM")
        self.horizontalLayout.addWidget(self.pushButton_open_storm)
        spacerItem1 = QtWidgets.QSpacerItem(300, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton_open_matrix = QtWidgets.QPushButton(self.widget)
        self.pushButton_open_matrix.setObjectName("OpenMatrix")
        self.pushButton_open_matrix.setEnabled(False)
        self.horizontalLayout.addWidget(self.pushButton_open_matrix)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.gridLayout)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.widget)

        self.retranslateUi(Dialog_openSTORM)
        QtCore.QMetaObject.connectSlotsByName(Dialog_openSTORM)

    def retranslateUi(self, Dialog_openSTORM):
        Dialog_openSTORM.setWindowTitle(_translate("Dialog_openSTORM", "Open Storm File", None))
        self.groupBox_3.setTitle(_translate("Dialog_openSTORM", "STORM input", None))
        self.groupBox_2.setTitle(_translate("Dialog_openSTORM", "Translation Matrix", None))
        self.pushButton_open_storm.setText(_translate("Dialog_openSTORM", "Open STORM", None))
        self.pushButton_open_matrix.setText(_translate("Dialog_openSTORM", "Open Matrix", None))
