# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(951, 735)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icons/molecules2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QWidget{\n"
"    background-color: rgb(67, 67, 67);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QScrollArea{\n"
"    border: 0px;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QToolTip { \n"
"    color: #000;\n"
"}\n"
"QTabBar::tab {\n"
"    border: 1px #fff;\n"
"    border-top-style :solid;\n"
"    border-right-style :solid; \n"
"    border-bottom-style :none; \n"
"    border-left-style :solid;\n"
"    padding: 4px 6px;\n"
"    margin: 0px 4px;\n"
"/*\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    min-width: 90px;\n"
"    min-height: 75px;\n"
"*/    \n"
"}\n"
"\n"
"QTabBar::tab:selected{\n"
"    background-color: #000000;\n"
"    border: 1px blue;\n"
"    border-top-style :solid;\n"
"    border-right-style :solid; \n"
"    border-bottom-style :none; \n"
"    border-left-style :solid;\n"
"    padding: 4px 6px;\n"
"}\n"
"QTabBar::tab:!selected {\n"
"    margin-top: 4px; }\n"
"/*QGroupBox:title{\n"
"    color: #ffaa00;\n"
"}*/\n"
"\n"
"QGroupBox{\n"
"    color: #ffaa00;\n"
"    \n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 235))
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.frame_images_actions = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.frame_images_actions.setFont(font)
        self.frame_images_actions.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_images_actions.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_images_actions.setLineWidth(1)
        self.frame_images_actions.setObjectName("frame_images_actions")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_images_actions)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_storm_top_controls = QtWidgets.QGroupBox(self.frame_images_actions)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBox_storm_top_controls.setFont(font)
        self.groupBox_storm_top_controls.setStyleSheet("")
        self.groupBox_storm_top_controls.setFlat(False)
        self.groupBox_storm_top_controls.setCheckable(False)
        self.groupBox_storm_top_controls.setObjectName("groupBox_storm_top_controls")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_storm_top_controls)
        self.verticalLayout_5.setContentsMargins(1, 0, 1, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tabWidget_storm_tabs = QtWidgets.QTabWidget(self.groupBox_storm_top_controls)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget_storm_tabs.setFont(font)
        self.tabWidget_storm_tabs.setStyleSheet("")
        self.tabWidget_storm_tabs.setUsesScrollButtons(True)
        self.tabWidget_storm_tabs.setDocumentMode(True)
        self.tabWidget_storm_tabs.setObjectName("tabWidget_storm_tabs")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_open_storm = QtWidgets.QPushButton(self.tab)
        self.pushButton_open_storm.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_open_storm.setObjectName("pushButton_open_storm")
        self.horizontalLayout_10.addWidget(self.pushButton_open_storm)
        self.checkBox_trans_Matrix = QtWidgets.QCheckBox(self.tab)
        self.checkBox_trans_Matrix.setObjectName("checkBox_trans_Matrix")
        self.horizontalLayout_10.addWidget(self.checkBox_trans_Matrix)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.pushButton_close_all_storm = QtWidgets.QPushButton(self.tab)
        self.pushButton_close_all_storm.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_close_all_storm.setObjectName("pushButton_close_all_storm")
        self.horizontalLayout_10.addWidget(self.pushButton_close_all_storm)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.storm_images_list = QtWidgets.QListWidget(self.tab)
        self.storm_images_list.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.storm_images_list.setObjectName("storm_images_list")
        self.verticalLayout.addWidget(self.storm_images_list)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_show_storm = QtWidgets.QPushButton(self.tab)
        self.pushButton_show_storm.setObjectName("pushButton_show_storm")
        self.horizontalLayout_6.addWidget(self.pushButton_show_storm)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.pushButton_unload_storm = QtWidgets.QPushButton(self.tab)
        self.pushButton_unload_storm.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_unload_storm.setObjectName("pushButton_unload_storm")
        self.horizontalLayout_6.addWidget(self.pushButton_unload_storm)
        self.pushButton_close_storm = QtWidgets.QPushButton(self.tab)
        self.pushButton_close_storm.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_close_storm.setObjectName("pushButton_close_storm")
        self.horizontalLayout_6.addWidget(self.pushButton_close_storm)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icons/selection13.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_storm_tabs.addTab(self.tab, icon1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 406, 111))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_2.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_2.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.widget_5 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_7.setContentsMargins(5, 0, 5, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_storm_config_fileheader = QtWidgets.QGroupBox(self.widget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_storm_config_fileheader.setFont(font)
        self.groupBox_storm_config_fileheader.setFlat(True)
        self.groupBox_storm_config_fileheader.setObjectName("groupBox_storm_config_fileheader")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_storm_config_fileheader)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_26 = QtWidgets.QLabel(self.groupBox_storm_config_fileheader)
        self.label_26.setObjectName("label_26")
        self.gridLayout_9.addWidget(self.label_26, 2, 0, 1, 1)
        self.spinBox_storm_config_fileheader_z = QtWidgets.QSpinBox(self.groupBox_storm_config_fileheader)
        self.spinBox_storm_config_fileheader_z.setProperty("value", 3)
        self.spinBox_storm_config_fileheader_z.setObjectName("spinBox_storm_config_fileheader_z")
        self.gridLayout_9.addWidget(self.spinBox_storm_config_fileheader_z, 5, 1, 1, 1)
        self.spinBox_storm_config_fileheader_frame = QtWidgets.QSpinBox(self.groupBox_storm_config_fileheader)
        self.spinBox_storm_config_fileheader_frame.setProperty("value", 5)
        self.spinBox_storm_config_fileheader_frame.setObjectName("spinBox_storm_config_fileheader_frame")
        self.gridLayout_9.addWidget(self.spinBox_storm_config_fileheader_frame, 3, 6, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.groupBox_storm_config_fileheader)
        self.label_28.setObjectName("label_28")
        self.gridLayout_9.addWidget(self.label_28, 3, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.groupBox_storm_config_fileheader)
        self.label_32.setObjectName("label_32")
        self.gridLayout_9.addWidget(self.label_32, 3, 5, 1, 1)
        self.spinBox_storm_config_fileheader_localization_precision = QtWidgets.QSpinBox(self.groupBox_storm_config_fileheader)
        self.spinBox_storm_config_fileheader_localization_precision.setProperty("value", 0)
        self.spinBox_storm_config_fileheader_localization_precision.setObjectName("spinBox_storm_config_fileheader_localization_precision")
        self.gridLayout_9.addWidget(self.spinBox_storm_config_fileheader_localization_precision, 3, 3, 1, 1)
        self.spinBox_storm_config_fileheader_y = QtWidgets.QSpinBox(self.groupBox_storm_config_fileheader)
        self.spinBox_storm_config_fileheader_y.setMinimum(1)
        self.spinBox_storm_config_fileheader_y.setProperty("value", 2)
        self.spinBox_storm_config_fileheader_y.setObjectName("spinBox_storm_config_fileheader_y")
        self.gridLayout_9.addWidget(self.spinBox_storm_config_fileheader_y, 3, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.groupBox_storm_config_fileheader)
        self.label_29.setObjectName("label_29")
        self.gridLayout_9.addWidget(self.label_29, 2, 2, 1, 1)
        self.spinBox_storm_config_fileheader_photon = QtWidgets.QSpinBox(self.groupBox_storm_config_fileheader)
        self.spinBox_storm_config_fileheader_photon.setProperty("value", 4)
        self.spinBox_storm_config_fileheader_photon.setObjectName("spinBox_storm_config_fileheader_photon")
        self.gridLayout_9.addWidget(self.spinBox_storm_config_fileheader_photon, 2, 6, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.groupBox_storm_config_fileheader)
        self.label_31.setObjectName("label_31")
        self.gridLayout_9.addWidget(self.label_31, 2, 5, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem2, 2, 7, 1, 1)
        self.spinBox_storm_config_fileheader_channel_name = QtWidgets.QSpinBox(self.groupBox_storm_config_fileheader)
        self.spinBox_storm_config_fileheader_channel_name.setProperty("value", 0)
        self.spinBox_storm_config_fileheader_channel_name.setObjectName("spinBox_storm_config_fileheader_channel_name")
        self.gridLayout_9.addWidget(self.spinBox_storm_config_fileheader_channel_name, 2, 3, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.groupBox_storm_config_fileheader)
        self.label_27.setObjectName("label_27")
        self.gridLayout_9.addWidget(self.label_27, 5, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.groupBox_storm_config_fileheader)
        self.label_30.setObjectName("label_30")
        self.gridLayout_9.addWidget(self.label_30, 3, 2, 1, 1)
        self.spinBox_storm_config_fileheader_x = QtWidgets.QSpinBox(self.groupBox_storm_config_fileheader)
        self.spinBox_storm_config_fileheader_x.setMinimum(1)
        self.spinBox_storm_config_fileheader_x.setProperty("value", 1)
        self.spinBox_storm_config_fileheader_x.setObjectName("spinBox_storm_config_fileheader_x")
        self.gridLayout_9.addWidget(self.spinBox_storm_config_fileheader_x, 2, 1, 1, 1)
        self.verticalLayout_7.addWidget(self.groupBox_storm_config_fileheader)
        self.verticalLayout_19.addWidget(self.widget_5)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.addWidget(self.scrollArea_2)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.groupBox_storm_config_display = QtWidgets.QGroupBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_storm_config_display.setFont(font)
        self.groupBox_storm_config_display.setFlat(True)
        self.groupBox_storm_config_display.setCheckable(True)
        self.groupBox_storm_config_display.setObjectName("groupBox_storm_config_display")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_storm_config_display)
        self.formLayout.setObjectName("formLayout")
        self.label_14 = QtWidgets.QLabel(self.groupBox_storm_config_display)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.spinBox_storm_config_dot_size = QtWidgets.QSpinBox(self.groupBox_storm_config_display)
        self.spinBox_storm_config_dot_size.setMinimum(1)
        self.spinBox_storm_config_dot_size.setMaximum(100)
        self.spinBox_storm_config_dot_size.setProperty("value", 30)
        self.spinBox_storm_config_dot_size.setObjectName("spinBox_storm_config_dot_size")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox_storm_config_dot_size)
        self.horizontalLayout_13.addWidget(self.groupBox_storm_config_display)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem3)
        self.pushButton_apply_storm_config = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_apply_storm_config.setObjectName("pushButton_apply_storm_config")
        self.horizontalLayout_13.addWidget(self.pushButton_apply_storm_config)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icons/settings48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_storm_tabs.addTab(self.tab_2, icon2, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_6)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 389, 206))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_3.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_3.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.widget_3 = QtWidgets.QWidget(self.scrollAreaWidgetContents_3)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_9.setContentsMargins(5, 0, 5, 0)
        self.verticalLayout_9.setSpacing(10)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.groupBox_storm_filter_z = QtWidgets.QGroupBox(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_storm_filter_z.setFont(font)
        self.groupBox_storm_filter_z.setFlat(True)
        self.groupBox_storm_filter_z.setCheckable(True)
        self.groupBox_storm_filter_z.setChecked(False)
        self.groupBox_storm_filter_z.setObjectName("groupBox_storm_filter_z")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_storm_filter_z)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_storm_filter_z)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.spinBox_storm_filter_z_from = QtWidgets.QSpinBox(self.groupBox_storm_filter_z)
        self.spinBox_storm_filter_z_from.setMinimum(-10000)
        self.spinBox_storm_filter_z_from.setMaximum(10000)
        self.spinBox_storm_filter_z_from.setSingleStep(10)
        self.spinBox_storm_filter_z_from.setProperty("value", -300)
        self.spinBox_storm_filter_z_from.setObjectName("spinBox_storm_filter_z_from")
        self.horizontalLayout_2.addWidget(self.spinBox_storm_filter_z_from)
        self.label_2 = QtWidgets.QLabel(self.groupBox_storm_filter_z)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spinBox_storm_filter_z_to = QtWidgets.QSpinBox(self.groupBox_storm_filter_z)
        self.spinBox_storm_filter_z_to.setMinimum(-10000)
        self.spinBox_storm_filter_z_to.setMaximum(10000)
        self.spinBox_storm_filter_z_to.setSingleStep(10)
        self.spinBox_storm_filter_z_to.setProperty("value", 300)
        self.spinBox_storm_filter_z_to.setObjectName("spinBox_storm_filter_z_to")
        self.horizontalLayout_2.addWidget(self.spinBox_storm_filter_z_to)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_9.addWidget(self.groupBox_storm_filter_z)
        self.groupBox_storm_filter_photon = QtWidgets.QGroupBox(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_storm_filter_photon.setFont(font)
        self.groupBox_storm_filter_photon.setFlat(True)
        self.groupBox_storm_filter_photon.setCheckable(True)
        self.groupBox_storm_filter_photon.setChecked(False)
        self.groupBox_storm_filter_photon.setObjectName("groupBox_storm_filter_photon")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.groupBox_storm_filter_photon)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_3 = QtWidgets.QLabel(self.groupBox_storm_filter_photon)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_15.addWidget(self.label_3)
        self.spinBox_storm_filter_photon_from = QtWidgets.QSpinBox(self.groupBox_storm_filter_photon)
        self.spinBox_storm_filter_photon_from.setMinimum(0)
        self.spinBox_storm_filter_photon_from.setMaximum(10000000)
        self.spinBox_storm_filter_photon_from.setSingleStep(100)
        self.spinBox_storm_filter_photon_from.setProperty("value", 0)
        self.spinBox_storm_filter_photon_from.setObjectName("spinBox_storm_filter_photon_from")
        self.horizontalLayout_15.addWidget(self.spinBox_storm_filter_photon_from)
        self.label_7 = QtWidgets.QLabel(self.groupBox_storm_filter_photon)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_15.addWidget(self.label_7)
        self.spinBox_storm_filter_photon_to = QtWidgets.QSpinBox(self.groupBox_storm_filter_photon)
        self.spinBox_storm_filter_photon_to.setMaximum(10000000)
        self.spinBox_storm_filter_photon_to.setSingleStep(100)
        self.spinBox_storm_filter_photon_to.setProperty("value", 5000000)
        self.spinBox_storm_filter_photon_to.setObjectName("spinBox_storm_filter_photon_to")
        self.horizontalLayout_15.addWidget(self.spinBox_storm_filter_photon_to)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem5)
        self.verticalLayout_9.addWidget(self.groupBox_storm_filter_photon)
        self.groupBox_storm_filter_frame = QtWidgets.QGroupBox(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_storm_filter_frame.setFont(font)
        self.groupBox_storm_filter_frame.setFlat(True)
        self.groupBox_storm_filter_frame.setCheckable(True)
        self.groupBox_storm_filter_frame.setChecked(False)
        self.groupBox_storm_filter_frame.setObjectName("groupBox_storm_filter_frame")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.groupBox_storm_filter_frame)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_9 = QtWidgets.QLabel(self.groupBox_storm_filter_frame)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_16.addWidget(self.label_9)
        self.spinBox_storm_filter_frame_from = QtWidgets.QSpinBox(self.groupBox_storm_filter_frame)
        self.spinBox_storm_filter_frame_from.setMinimum(0)
        self.spinBox_storm_filter_frame_from.setMaximum(1000000)
        self.spinBox_storm_filter_frame_from.setSingleStep(10)
        self.spinBox_storm_filter_frame_from.setProperty("value", 0)
        self.spinBox_storm_filter_frame_from.setObjectName("spinBox_storm_filter_frame_from")
        self.horizontalLayout_16.addWidget(self.spinBox_storm_filter_frame_from)
        self.label_11 = QtWidgets.QLabel(self.groupBox_storm_filter_frame)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_16.addWidget(self.label_11)
        self.spinBox_storm_filter_frame_to = QtWidgets.QSpinBox(self.groupBox_storm_filter_frame)
        self.spinBox_storm_filter_frame_to.setMaximum(1000000)
        self.spinBox_storm_filter_frame_to.setSingleStep(10)
        self.spinBox_storm_filter_frame_to.setProperty("value", 5000)
        self.spinBox_storm_filter_frame_to.setObjectName("spinBox_storm_filter_frame_to")
        self.horizontalLayout_16.addWidget(self.spinBox_storm_filter_frame_to)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem6)
        self.verticalLayout_9.addWidget(self.groupBox_storm_filter_frame)
        self.groupBox_storm_filter_localdensity = QtWidgets.QGroupBox(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_storm_filter_localdensity.setFont(font)
        self.groupBox_storm_filter_localdensity.setFlat(True)
        self.groupBox_storm_filter_localdensity.setCheckable(True)
        self.groupBox_storm_filter_localdensity.setChecked(False)
        self.groupBox_storm_filter_localdensity.setObjectName("groupBox_storm_filter_localdensity")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_storm_filter_localdensity)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.widget_11 = QtWidgets.QWidget(self.groupBox_storm_filter_localdensity)
        self.widget_11.setObjectName("widget_11")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_11)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.doubleSpinBox_storm_filter_localdensity_maxradius = QtWidgets.QDoubleSpinBox(self.widget_11)
        self.doubleSpinBox_storm_filter_localdensity_maxradius.setMaximum(100000.0)
        self.doubleSpinBox_storm_filter_localdensity_maxradius.setSingleStep(10.0)
        self.doubleSpinBox_storm_filter_localdensity_maxradius.setProperty("value", 100.0)
        self.doubleSpinBox_storm_filter_localdensity_maxradius.setObjectName("doubleSpinBox_storm_filter_localdensity_maxradius")
        self.gridLayout_6.addWidget(self.doubleSpinBox_storm_filter_localdensity_maxradius, 1, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem7, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget_11)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 1, 0, 1, 1)
        self.spinBox_storm_filter_localdensity_min_num = QtWidgets.QSpinBox(self.widget_11)
        self.spinBox_storm_filter_localdensity_min_num.setSuffix("")
        self.spinBox_storm_filter_localdensity_min_num.setMaximum(1000)
        self.spinBox_storm_filter_localdensity_min_num.setProperty("value", 3)
        self.spinBox_storm_filter_localdensity_min_num.setObjectName("spinBox_storm_filter_localdensity_min_num")
        self.gridLayout_6.addWidget(self.spinBox_storm_filter_localdensity_min_num, 0, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem8, 0, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widget_11)
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.widget_11, 0, 0, 1, 1)
        self.verticalLayout_9.addWidget(self.groupBox_storm_filter_localdensity)
        self.verticalLayout_10.addWidget(self.widget_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_8.addWidget(self.scrollArea)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem9)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem10)
        self.pushButton_apply_storm_filters = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_apply_storm_filters.setObjectName("pushButton_apply_storm_filters")
        self.horizontalLayout_4.addWidget(self.pushButton_apply_storm_filters)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/icons/filter15.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_storm_tabs.addTab(self.tab_6, icon3, "")
        self.verticalLayout_5.addWidget(self.tabWidget_storm_tabs)
        self.horizontalLayout.addWidget(self.groupBox_storm_top_controls)
        self.widget_2 = QtWidgets.QWidget(self.frame_images_actions)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem11)
        self.pushButton_prev_batch = QtWidgets.QPushButton(self.widget_2)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/icons/arrow218.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_prev_batch.setIcon(icon4)
        self.pushButton_prev_batch.setObjectName("pushButton_prev_batch")
        self.verticalLayout_16.addWidget(self.pushButton_prev_batch)
        self.pushButton_next_batch = QtWidgets.QPushButton(self.widget_2)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/icons/arrow167.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_next_batch.setIcon(icon5)
        self.pushButton_next_batch.setObjectName("pushButton_next_batch")
        self.verticalLayout_16.addWidget(self.pushButton_next_batch)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem12)
        self.horizontalLayout.addWidget(self.widget_2)
        self.groupBox_confocal_top_controls = QtWidgets.QGroupBox(self.frame_images_actions)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_confocal_top_controls.setFont(font)
        self.groupBox_confocal_top_controls.setObjectName("groupBox_confocal_top_controls")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_confocal_top_controls)
        self.verticalLayout_6.setContentsMargins(1, 0, 1, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tabWidget_confocal_tabs = QtWidgets.QTabWidget(self.groupBox_confocal_top_controls)
        self.tabWidget_confocal_tabs.setDocumentMode(True)
        self.tabWidget_confocal_tabs.setObjectName("tabWidget_confocal_tabs")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_open_confocal = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_open_confocal.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_open_confocal.setObjectName("pushButton_open_confocal")
        self.horizontalLayout_9.addWidget(self.pushButton_open_confocal)
        self.checkBox_flip_lr = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_flip_lr.setObjectName("checkBox_flip_lr")
        self.horizontalLayout_9.addWidget(self.checkBox_flip_lr)
        self.checkBox_flip_ud = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_flip_ud.setObjectName("checkBox_flip_ud")
        self.horizontalLayout_9.addWidget(self.checkBox_flip_ud)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem13)
        self.pushButton_close_all_confocal = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_close_all_confocal.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_close_all_confocal.setObjectName("pushButton_close_all_confocal")
        self.horizontalLayout_9.addWidget(self.pushButton_close_all_confocal)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.confocal_images_list = QtWidgets.QListWidget(self.tab_3)
        self.confocal_images_list.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.confocal_images_list.setObjectName("confocal_images_list")
        self.verticalLayout_2.addWidget(self.confocal_images_list)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_show_confocal = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_show_confocal.setObjectName("pushButton_show_confocal")
        self.horizontalLayout_7.addWidget(self.pushButton_show_confocal)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem14)
        self.pushButton_unload_confocal = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_unload_confocal.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_unload_confocal.setObjectName("pushButton_unload_confocal")
        self.horizontalLayout_7.addWidget(self.pushButton_unload_confocal)
        self.pushButton_close_confocal = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_close_confocal.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_close_confocal.setObjectName("pushButton_close_confocal")
        self.horizontalLayout_7.addWidget(self.pushButton_close_confocal)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.tabWidget_confocal_tabs.addTab(self.tab_3, icon1, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_confocal_config_resize_min_2 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_confocal_config_resize_min_2.setStyleSheet("")
        self.groupBox_confocal_config_resize_min_2.setFlat(True)
        self.groupBox_confocal_config_resize_min_2.setObjectName("groupBox_confocal_config_resize_min_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_confocal_config_resize_min_2)
        self.gridLayout_4.setContentsMargins(-1, 2, -1, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.radioButton_confocal_config_min_nearest = QtWidgets.QRadioButton(self.groupBox_confocal_config_resize_min_2)
        self.radioButton_confocal_config_min_nearest.setMinimumSize(QtCore.QSize(0, 0))
        self.radioButton_confocal_config_min_nearest.setBaseSize(QtCore.QSize(0, 0))
        self.radioButton_confocal_config_min_nearest.setChecked(True)
        self.radioButton_confocal_config_min_nearest.setAutoExclusive(True)
        self.radioButton_confocal_config_min_nearest.setObjectName("radioButton_confocal_config_min_nearest")
        self.gridLayout_4.addWidget(self.radioButton_confocal_config_min_nearest, 0, 0, 1, 1)
        self.radioButton_confocal_config_min_linear = QtWidgets.QRadioButton(self.groupBox_confocal_config_resize_min_2)
        self.radioButton_confocal_config_min_linear.setChecked(False)
        self.radioButton_confocal_config_min_linear.setAutoExclusive(True)
        self.radioButton_confocal_config_min_linear.setObjectName("radioButton_confocal_config_min_linear")
        self.gridLayout_4.addWidget(self.radioButton_confocal_config_min_linear, 0, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_confocal_config_resize_min_2)
        self.groupBox_confocal_config_resize_mag = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_confocal_config_resize_mag.setFlat(True)
        self.groupBox_confocal_config_resize_mag.setObjectName("groupBox_confocal_config_resize_mag")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.groupBox_confocal_config_resize_mag)
        self.horizontalLayout_20.setContentsMargins(-1, 3, -1, 0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.radioButton_confocal_config_mag_nearest = QtWidgets.QRadioButton(self.groupBox_confocal_config_resize_mag)
        self.radioButton_confocal_config_mag_nearest.setChecked(True)
        self.radioButton_confocal_config_mag_nearest.setObjectName("radioButton_confocal_config_mag_nearest")
        self.horizontalLayout_20.addWidget(self.radioButton_confocal_config_mag_nearest)
        self.radioButton_confocal_config_mag_linear = QtWidgets.QRadioButton(self.groupBox_confocal_config_resize_mag)
        self.radioButton_confocal_config_mag_linear.setChecked(False)
        self.radioButton_confocal_config_mag_linear.setAutoExclusive(True)
        self.radioButton_confocal_config_mag_linear.setObjectName("radioButton_confocal_config_mag_linear")
        self.horizontalLayout_20.addWidget(self.radioButton_confocal_config_mag_linear)
        self.verticalLayout_4.addWidget(self.groupBox_confocal_config_resize_mag)
        self.groupBox_confocal_config_calibration = QtWidgets.QGroupBox(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_confocal_config_calibration.setFont(font)
        self.groupBox_confocal_config_calibration.setFlat(True)
        self.groupBox_confocal_config_calibration.setObjectName("groupBox_confocal_config_calibration")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.groupBox_confocal_config_calibration)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_4 = QtWidgets.QLabel(self.groupBox_confocal_config_calibration)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_12.addWidget(self.label_4)
        self.doubleSpinBox_confocal_config_calibration_px = QtWidgets.QDoubleSpinBox(self.groupBox_confocal_config_calibration)
        self.doubleSpinBox_confocal_config_calibration_px.setDecimals(6)
        self.doubleSpinBox_confocal_config_calibration_px.setMaximum(2.0)
        self.doubleSpinBox_confocal_config_calibration_px.setSingleStep(0.001)
        self.doubleSpinBox_confocal_config_calibration_px.setProperty("value", 0.078)
        self.doubleSpinBox_confocal_config_calibration_px.setObjectName("doubleSpinBox_confocal_config_calibration_px")
        self.horizontalLayout_12.addWidget(self.doubleSpinBox_confocal_config_calibration_px)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem15)
        self.verticalLayout_4.addWidget(self.groupBox_confocal_config_calibration)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem16)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem17)
        self.pushButton_apply_confocal_config = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_apply_confocal_config.setObjectName("pushButton_apply_confocal_config")
        self.horizontalLayout_11.addWidget(self.pushButton_apply_confocal_config)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.tabWidget_confocal_tabs.addTab(self.tab_4, icon2, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.groupBox_confocal_display_appear = QtWidgets.QGroupBox(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_confocal_display_appear.setFont(font)
        self.groupBox_confocal_display_appear.setFlat(True)
        self.groupBox_confocal_display_appear.setObjectName("groupBox_confocal_display_appear")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_confocal_display_appear)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox_confocal_display_appear)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.doubleSpinBox_confocal_display_appear_transparency = QtWidgets.QDoubleSpinBox(self.groupBox_confocal_display_appear)
        self.doubleSpinBox_confocal_display_appear_transparency.setMaximum(1.0)
        self.doubleSpinBox_confocal_display_appear_transparency.setSingleStep(0.1)
        self.doubleSpinBox_confocal_display_appear_transparency.setProperty("value", 0.7)
        self.doubleSpinBox_confocal_display_appear_transparency.setObjectName("doubleSpinBox_confocal_display_appear_transparency")
        self.horizontalLayout_3.addWidget(self.doubleSpinBox_confocal_display_appear_transparency)
        self.label_5 = QtWidgets.QLabel(self.groupBox_confocal_display_appear)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.spinBox_confocal_display_appear_zposition = QtWidgets.QSpinBox(self.groupBox_confocal_display_appear)
        self.spinBox_confocal_display_appear_zposition.setMinimum(-10000)
        self.spinBox_confocal_display_appear_zposition.setMaximum(100000)
        self.spinBox_confocal_display_appear_zposition.setSingleStep(0)
        self.spinBox_confocal_display_appear_zposition.setProperty("value", 0)
        self.spinBox_confocal_display_appear_zposition.setObjectName("spinBox_confocal_display_appear_zposition")
        self.horizontalLayout_3.addWidget(self.spinBox_confocal_display_appear_zposition)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem18)
        self.verticalLayout_12.addWidget(self.groupBox_confocal_display_appear)
        self.groupBox_confocal_display_offset = QtWidgets.QGroupBox(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_confocal_display_offset.setFont(font)
        self.groupBox_confocal_display_offset.setFlat(True)
        self.groupBox_confocal_display_offset.setObjectName("groupBox_confocal_display_offset")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.groupBox_confocal_display_offset)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_12 = QtWidgets.QLabel(self.groupBox_confocal_display_offset)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_17.addWidget(self.label_12)
        self.doubleSpinBox_confocal_display_offset_x = QtWidgets.QDoubleSpinBox(self.groupBox_confocal_display_offset)
        self.doubleSpinBox_confocal_display_offset_x.setDecimals(0)
        self.doubleSpinBox_confocal_display_offset_x.setMinimum(-100000.0)
        self.doubleSpinBox_confocal_display_offset_x.setMaximum(100000.0)
        self.doubleSpinBox_confocal_display_offset_x.setSingleStep(10.0)
        self.doubleSpinBox_confocal_display_offset_x.setObjectName("doubleSpinBox_confocal_display_offset_x")
        self.horizontalLayout_17.addWidget(self.doubleSpinBox_confocal_display_offset_x)
        self.label_13 = QtWidgets.QLabel(self.groupBox_confocal_display_offset)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_17.addWidget(self.label_13)
        self.doubleSpinBox_confocal_display_offset_y = QtWidgets.QDoubleSpinBox(self.groupBox_confocal_display_offset)
        self.doubleSpinBox_confocal_display_offset_y.setDecimals(0)
        self.doubleSpinBox_confocal_display_offset_y.setMinimum(-100000.0)
        self.doubleSpinBox_confocal_display_offset_y.setMaximum(100000.0)
        self.doubleSpinBox_confocal_display_offset_y.setSingleStep(10.0)
        self.doubleSpinBox_confocal_display_offset_y.setObjectName("doubleSpinBox_confocal_display_offset_y")
        self.horizontalLayout_17.addWidget(self.doubleSpinBox_confocal_display_offset_y)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem19)
        self.verticalLayout_12.addWidget(self.groupBox_confocal_display_offset)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem20)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem21)
        self.pushButton_apply_confocal_display = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_apply_confocal_display.setObjectName("pushButton_apply_confocal_display")
        self.horizontalLayout_5.addWidget(self.pushButton_apply_confocal_display)
        self.verticalLayout_12.addLayout(self.horizontalLayout_5)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/icons/landscape.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_confocal_tabs.addTab(self.tab_5, icon6, "")
        self.verticalLayout_6.addWidget(self.tabWidget_confocal_tabs)
        self.horizontalLayout.addWidget(self.groupBox_confocal_top_controls)
        self.horizontalLayout_14.addWidget(self.frame_images_actions)
        MainWindow.setCentralWidget(self.centralwidget)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget.sizePolicy().hasHeightForWidth())
        self.dockWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.dockWidget.setFont(font)
        self.dockWidget.setFloating(False)
        self.dockWidget.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockWidget.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetContents.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents.setSizePolicy(sizePolicy)
        self.dockWidgetContents.setMinimumSize(QtCore.QSize(0, 427))
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.viewer_container = QtWidgets.QWidget(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewer_container.sizePolicy().hasHeightForWidth())
        self.viewer_container.setSizePolicy(sizePolicy)
        self.viewer_container.setObjectName("viewer_container")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.viewer_container)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.viewer_container_layout = QtWidgets.QVBoxLayout()
        self.viewer_container_layout.setSpacing(6)
        self.viewer_container_layout.setObjectName("viewer_container_layout")
        self.verticalLayout_13.addLayout(self.viewer_container_layout)
        self.verticalLayout_11.addWidget(self.viewer_container)
        self.widget_6 = QtWidgets.QWidget(self.dockWidgetContents)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.groupBox_storm_bottom_controls = QtWidgets.QGroupBox(self.widget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_storm_bottom_controls.setFont(font)
        self.groupBox_storm_bottom_controls.setStyleSheet("border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.groupBox_storm_bottom_controls.setFlat(True)
        self.groupBox_storm_bottom_controls.setObjectName("groupBox_storm_bottom_controls")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.groupBox_storm_bottom_controls)
        self.verticalLayout_14.setContentsMargins(1, 0, 1, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.widget = QtWidgets.QWidget(self.groupBox_storm_bottom_controls)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.widget.setFont(font)
        self.widget.setStyleSheet("margin: 0;")
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBox_storm_channel1 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_storm_channel1.setEnabled(False)
        self.checkBox_storm_channel1.setChecked(False)
        self.checkBox_storm_channel1.setObjectName("checkBox_storm_channel1")
        self.gridLayout_2.addWidget(self.checkBox_storm_channel1, 0, 1, 1, 1)
        self.checkBox_storm_channel3 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_storm_channel3.setEnabled(False)
        self.checkBox_storm_channel3.setChecked(False)
        self.checkBox_storm_channel3.setObjectName("checkBox_storm_channel3")
        self.gridLayout_2.addWidget(self.checkBox_storm_channel3, 0, 3, 1, 1)
        self.checkBox_storm_channel0 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_storm_channel0.setEnabled(False)
        self.checkBox_storm_channel0.setChecked(False)
        self.checkBox_storm_channel0.setObjectName("checkBox_storm_channel0")
        self.gridLayout_2.addWidget(self.checkBox_storm_channel0, 0, 0, 1, 1)
        self.checkBox_storm_channel2 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_storm_channel2.setEnabled(False)
        self.checkBox_storm_channel2.setChecked(False)
        self.checkBox_storm_channel2.setObjectName("checkBox_storm_channel2")
        self.gridLayout_2.addWidget(self.checkBox_storm_channel2, 0, 2, 1, 1)
        self.comboBox_storm_channel1_color = QtWidgets.QComboBox(self.widget)
        self.comboBox_storm_channel1_color.setEnabled(False)
        self.comboBox_storm_channel1_color.setEditable(False)
        self.comboBox_storm_channel1_color.setObjectName("comboBox_storm_channel1_color")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icon/icons/square-rounded-32-r.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox_storm_channel1_color.addItem(icon7, "")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icon/icons/square-rounded-32-g.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox_storm_channel1_color.addItem(icon8, "")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icon/icons/square-rounded-32-b.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox_storm_channel1_color.addItem(icon9, "")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icon/icons/square-rounded-32-c.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox_storm_channel1_color.addItem(icon10, "")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icon/icons/square-rounded-32-m.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox_storm_channel1_color.addItem(icon11, "")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icon/icons/square-rounded-32-y.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox_storm_channel1_color.addItem(icon12, "")
        self.gridLayout_2.addWidget(self.comboBox_storm_channel1_color, 1, 1, 1, 1)
        self.comboBox_storm_channel0_color = QtWidgets.QComboBox(self.widget)
        self.comboBox_storm_channel0_color.setEnabled(False)
        self.comboBox_storm_channel0_color.setEditable(False)
        self.comboBox_storm_channel0_color.setObjectName("comboBox_storm_channel0_color")
        self.comboBox_storm_channel0_color.addItem(icon7, "")
        self.comboBox_storm_channel0_color.addItem(icon8, "")
        self.comboBox_storm_channel0_color.addItem(icon9, "")
        self.comboBox_storm_channel0_color.addItem(icon10, "")
        self.comboBox_storm_channel0_color.addItem(icon11, "")
        self.comboBox_storm_channel0_color.addItem(icon12, "")
        self.gridLayout_2.addWidget(self.comboBox_storm_channel0_color, 1, 0, 1, 1)
        self.comboBox_storm_channel2_color = QtWidgets.QComboBox(self.widget)
        self.comboBox_storm_channel2_color.setEnabled(False)
        self.comboBox_storm_channel2_color.setEditable(False)
        self.comboBox_storm_channel2_color.setObjectName("comboBox_storm_channel2_color")
        self.comboBox_storm_channel2_color.addItem(icon7, "")
        self.comboBox_storm_channel2_color.addItem(icon8, "")
        self.comboBox_storm_channel2_color.addItem(icon9, "")
        self.comboBox_storm_channel2_color.addItem(icon10, "")
        self.comboBox_storm_channel2_color.addItem(icon11, "")
        self.comboBox_storm_channel2_color.addItem(icon12, "")
        self.gridLayout_2.addWidget(self.comboBox_storm_channel2_color, 1, 2, 1, 1)
        self.comboBox_storm_channel3_color = QtWidgets.QComboBox(self.widget)
        self.comboBox_storm_channel3_color.setEnabled(False)
        self.comboBox_storm_channel3_color.setEditable(False)
        self.comboBox_storm_channel3_color.setObjectName("comboBox_storm_channel3_color")
        self.comboBox_storm_channel3_color.addItem(icon7, "")
        self.comboBox_storm_channel3_color.addItem(icon8, "")
        self.comboBox_storm_channel3_color.addItem(icon9, "")
        self.comboBox_storm_channel3_color.addItem(icon10, "")
        self.comboBox_storm_channel3_color.addItem(icon11, "")
        self.comboBox_storm_channel3_color.addItem(icon12, "")
        self.gridLayout_2.addWidget(self.comboBox_storm_channel3_color, 1, 3, 1, 1)
        self.label_storm_channel0_info = QtWidgets.QLabel(self.widget)
        self.label_storm_channel0_info.setObjectName("label_storm_channel0_info")
        self.gridLayout_2.addWidget(self.label_storm_channel0_info, 2, 0, 1, 1)
        self.label_storm_channel1_info = QtWidgets.QLabel(self.widget)
        self.label_storm_channel1_info.setObjectName("label_storm_channel1_info")
        self.gridLayout_2.addWidget(self.label_storm_channel1_info, 2, 1, 1, 1)
        self.label_storm_channel2_info = QtWidgets.QLabel(self.widget)
        self.label_storm_channel2_info.setObjectName("label_storm_channel2_info")
        self.gridLayout_2.addWidget(self.label_storm_channel2_info, 2, 2, 1, 1)
        self.label_storm_channel3_info = QtWidgets.QLabel(self.widget)
        self.label_storm_channel3_info.setObjectName("label_storm_channel3_info")
        self.gridLayout_2.addWidget(self.label_storm_channel3_info, 2, 3, 1, 1)
        self.verticalLayout_14.addWidget(self.widget)
        self.horizontalLayout_8.addWidget(self.groupBox_storm_bottom_controls)
        self.line_3 = QtWidgets.QFrame(self.widget_6)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_8.addWidget(self.line_3)
        self.groupBox_confocal_bottom_controls = QtWidgets.QGroupBox(self.widget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_confocal_bottom_controls.setFont(font)
        self.groupBox_confocal_bottom_controls.setStyleSheet("border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.groupBox_confocal_bottom_controls.setFlat(True)
        self.groupBox_confocal_bottom_controls.setObjectName("groupBox_confocal_bottom_controls")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.groupBox_confocal_bottom_controls)
        self.verticalLayout_15.setContentsMargins(1, 0, 1, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.widget_4 = QtWidgets.QWidget(self.groupBox_confocal_bottom_controls)
        self.widget_4.setStyleSheet("QSlider::groove:horizontal {\n"
"                    border: 1px solid #999999;\n"
"                    height: 8px; /* the groove expands to the size of the slider by default. by giving it a height, it has a fixed size */\n"
"                    width: 100px;\n"
"                    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #B1B1B1, stop:1 #c4c4c4);\n"
"                }\n"
"QSlider::handle::horizontal:disabled{\n"
"    background: #0033cc;\n"
"}\n"
"\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #b4b4b4,stop:1 #8f8f8f);\n"
"    border: 1px solid #5c5c5c;\n"
"    width: 18px;\n"
"    margin: -2px 0; /* handle is placed by default on the contents rect of the groove. Expand outside the groove */\n"
"    border-radius: 3px;}\n"
"QSlider::handle:horizontal:pressed {\n"
"    background: #0033cc;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"    background: white;\n"
"                }\n"
"")
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.comboBox_confocal_channel3_color = QtWidgets.QComboBox(self.widget_4)
        self.comboBox_confocal_channel3_color.setEnabled(False)
        self.comboBox_confocal_channel3_color.setEditable(False)
        self.comboBox_confocal_channel3_color.setObjectName("comboBox_confocal_channel3_color")
        self.comboBox_confocal_channel3_color.addItem(icon7, "")
        self.comboBox_confocal_channel3_color.addItem(icon8, "")
        self.comboBox_confocal_channel3_color.addItem(icon9, "")
        self.comboBox_confocal_channel3_color.addItem(icon10, "")
        self.comboBox_confocal_channel3_color.addItem(icon11, "")
        self.comboBox_confocal_channel3_color.addItem(icon12, "")
        self.gridLayout_3.addWidget(self.comboBox_confocal_channel3_color, 1, 3, 1, 1)
        self.comboBox_confocal_channel0_color = QtWidgets.QComboBox(self.widget_4)
        self.comboBox_confocal_channel0_color.setEnabled(False)
        self.comboBox_confocal_channel0_color.setEditable(False)
        self.comboBox_confocal_channel0_color.setObjectName("comboBox_confocal_channel0_color")
        self.comboBox_confocal_channel0_color.addItem(icon7, "")
        self.comboBox_confocal_channel0_color.addItem(icon8, "")
        self.comboBox_confocal_channel0_color.addItem(icon9, "")
        self.comboBox_confocal_channel0_color.addItem(icon10, "")
        self.comboBox_confocal_channel0_color.addItem(icon11, "")
        self.comboBox_confocal_channel0_color.addItem(icon12, "")
        self.gridLayout_3.addWidget(self.comboBox_confocal_channel0_color, 1, 0, 1, 1)
        self.comboBox_confocal_channel2_color = QtWidgets.QComboBox(self.widget_4)
        self.comboBox_confocal_channel2_color.setEnabled(False)
        self.comboBox_confocal_channel2_color.setEditable(False)
        self.comboBox_confocal_channel2_color.setObjectName("comboBox_confocal_channel2_color")
        self.comboBox_confocal_channel2_color.addItem(icon7, "")
        self.comboBox_confocal_channel2_color.addItem(icon8, "")
        self.comboBox_confocal_channel2_color.addItem(icon9, "")
        self.comboBox_confocal_channel2_color.addItem(icon10, "")
        self.comboBox_confocal_channel2_color.addItem(icon11, "")
        self.comboBox_confocal_channel2_color.addItem(icon12, "")
        self.gridLayout_3.addWidget(self.comboBox_confocal_channel2_color, 1, 2, 1, 1)
        self.slider_confocal_channel2_slice = QtWidgets.QSlider(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_confocal_channel2_slice.sizePolicy().hasHeightForWidth())
        self.slider_confocal_channel2_slice.setSizePolicy(sizePolicy)
        self.slider_confocal_channel2_slice.setOrientation(QtCore.Qt.Horizontal)
        self.slider_confocal_channel2_slice.setObjectName("slider_confocal_channel2_slice")
        self.gridLayout_3.addWidget(self.slider_confocal_channel2_slice, 2, 2, 1, 1)
        self.checkBox_confocal_channel0 = QtWidgets.QCheckBox(self.widget_4)
        self.checkBox_confocal_channel0.setEnabled(False)
        self.checkBox_confocal_channel0.setChecked(False)
        self.checkBox_confocal_channel0.setObjectName("checkBox_confocal_channel0")
        self.gridLayout_3.addWidget(self.checkBox_confocal_channel0, 0, 0, 1, 1)
        self.checkBox_confocal_channel2 = QtWidgets.QCheckBox(self.widget_4)
        self.checkBox_confocal_channel2.setEnabled(False)
        self.checkBox_confocal_channel2.setChecked(False)
        self.checkBox_confocal_channel2.setObjectName("checkBox_confocal_channel2")
        self.gridLayout_3.addWidget(self.checkBox_confocal_channel2, 0, 2, 1, 1)
        self.comboBox_confocal_channel1_color = QtWidgets.QComboBox(self.widget_4)
        self.comboBox_confocal_channel1_color.setEnabled(False)
        self.comboBox_confocal_channel1_color.setEditable(False)
        self.comboBox_confocal_channel1_color.setObjectName("comboBox_confocal_channel1_color")
        self.comboBox_confocal_channel1_color.addItem(icon7, "")
        self.comboBox_confocal_channel1_color.addItem(icon8, "")
        self.comboBox_confocal_channel1_color.addItem(icon9, "")
        self.comboBox_confocal_channel1_color.addItem(icon10, "")
        self.comboBox_confocal_channel1_color.addItem(icon11, "")
        self.comboBox_confocal_channel1_color.addItem(icon12, "")
        self.gridLayout_3.addWidget(self.comboBox_confocal_channel1_color, 1, 1, 1, 1)
        self.label_confocal_info = QtWidgets.QLabel(self.widget_4)
        self.label_confocal_info.setLineWidth(1)
        self.label_confocal_info.setObjectName("label_confocal_info")
        self.gridLayout_3.addWidget(self.label_confocal_info, 3, 0, 1, 4)
        self.checkBox_confocal_channel1 = QtWidgets.QCheckBox(self.widget_4)
        self.checkBox_confocal_channel1.setEnabled(False)
        self.checkBox_confocal_channel1.setStyleSheet("")
        self.checkBox_confocal_channel1.setChecked(False)
        self.checkBox_confocal_channel1.setObjectName("checkBox_confocal_channel1")
        self.gridLayout_3.addWidget(self.checkBox_confocal_channel1, 0, 1, 1, 1)
        self.slider_confocal_channel3_slice = QtWidgets.QSlider(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_confocal_channel3_slice.sizePolicy().hasHeightForWidth())
        self.slider_confocal_channel3_slice.setSizePolicy(sizePolicy)
        self.slider_confocal_channel3_slice.setOrientation(QtCore.Qt.Horizontal)
        self.slider_confocal_channel3_slice.setObjectName("slider_confocal_channel3_slice")
        self.gridLayout_3.addWidget(self.slider_confocal_channel3_slice, 2, 3, 1, 1)
        self.checkBox_confocal_channel3 = QtWidgets.QCheckBox(self.widget_4)
        self.checkBox_confocal_channel3.setEnabled(False)
        self.checkBox_confocal_channel3.setChecked(False)
        self.checkBox_confocal_channel3.setObjectName("checkBox_confocal_channel3")
        self.gridLayout_3.addWidget(self.checkBox_confocal_channel3, 0, 3, 1, 1)
        self.slider_confocal_channel0_slice = QtWidgets.QSlider(self.widget_4)
        self.slider_confocal_channel0_slice.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_confocal_channel0_slice.sizePolicy().hasHeightForWidth())
        self.slider_confocal_channel0_slice.setSizePolicy(sizePolicy)
        self.slider_confocal_channel0_slice.setStyleSheet("")
        self.slider_confocal_channel0_slice.setSingleStep(1)
        self.slider_confocal_channel0_slice.setSliderPosition(0)
        self.slider_confocal_channel0_slice.setOrientation(QtCore.Qt.Horizontal)
        self.slider_confocal_channel0_slice.setInvertedAppearance(False)
        self.slider_confocal_channel0_slice.setInvertedControls(True)
        self.slider_confocal_channel0_slice.setObjectName("slider_confocal_channel0_slice")
        self.gridLayout_3.addWidget(self.slider_confocal_channel0_slice, 2, 0, 1, 1)
        self.slider_confocal_channel1_slice = QtWidgets.QSlider(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_confocal_channel1_slice.sizePolicy().hasHeightForWidth())
        self.slider_confocal_channel1_slice.setSizePolicy(sizePolicy)
        self.slider_confocal_channel1_slice.setOrientation(QtCore.Qt.Horizontal)
        self.slider_confocal_channel1_slice.setObjectName("slider_confocal_channel1_slice")
        self.gridLayout_3.addWidget(self.slider_confocal_channel1_slice, 2, 1, 1, 1)
        self.verticalLayout_15.addWidget(self.widget_4)
        self.horizontalLayout_8.addWidget(self.groupBox_confocal_bottom_controls)
        self.verticalLayout_11.addWidget(self.widget_6)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.toolBar_2 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_2.setObjectName("toolBar_2")
        MainWindow.addToolBar(QtCore.Qt.RightToolBarArea, self.toolBar_2)
        self.toolBar_3 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_3.setStyleSheet("")
        self.toolBar_3.setObjectName("toolBar_3")
        MainWindow.addToolBar(QtCore.Qt.RightToolBarArea, self.toolBar_3)
        self.actionActiveContour_selector = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icon/icons/selection7.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionActiveContour_selector.setIcon(icon13)
        self.actionActiveContour_selector.setObjectName("actionActiveContour_selector")
        self.actionLUT_changer = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icon/icons/candlestick.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLUT_changer.setIcon(icon14)
        self.actionLUT_changer.setObjectName("actionLUT_changer")
        self.action = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/icon/icons/data61.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action.setIcon(icon15)
        self.action.setObjectName("action")
        self.actionVividSTORM_help = QtWidgets.QAction(MainWindow)
        self.actionVividSTORM_help.setObjectName("actionVividSTORM_help")
        self.actionAbout_VividSTORM = QtWidgets.QAction(MainWindow)
        self.actionAbout_VividSTORM.setObjectName("actionAbout_VividSTORM")
        self.actionDots = QtWidgets.QAction(MainWindow)
        self.actionDots.setCheckable(False)
        self.actionDots.setChecked(False)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/icon/icons/chart14.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDots.setIcon(icon16)
        self.actionDots.setObjectName("actionDots")
        self.actionGaussian = QtWidgets.QAction(MainWindow)
        self.actionGaussian.setCheckable(False)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/icon/icons/line47.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGaussian.setIcon(icon17)
        self.actionGaussian.setObjectName("actionGaussian")
        self.action3D = QtWidgets.QAction(MainWindow)
        self.action3D.setChecked(False)
        self.action3D.setEnabled(True)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/icon/icons/3d4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action3D.setIcon(icon18)
        self.action3D.setObjectName("action3D")
        self.actionShow_1_m_scale = QtWidgets.QAction(MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/icon/icons/scale6.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShow_1_m_scale.setIcon(icon19)
        self.actionShow_1_m_scale.setObjectName("actionShow_1_m_scale")
        self.actionOpen_STORM_files = QtWidgets.QAction(MainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/icon/icons/file98.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_STORM_files.setIcon(icon20)
        self.actionOpen_STORM_files.setObjectName("actionOpen_STORM_files")
        self.actionOpen_Confocal_files = QtWidgets.QAction(MainWindow)
        self.actionOpen_Confocal_files.setIcon(icon20)
        self.actionOpen_Confocal_files.setObjectName("actionOpen_Confocal_files")
        self.actionExport_As_Image = QtWidgets.QAction(MainWindow)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/icon/icons/export2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExport_As_Image.setIcon(icon21)
        self.actionExport_As_Image.setObjectName("actionExport_As_Image")
        self.actionClose_STORM_files = QtWidgets.QAction(MainWindow)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/icon/icons/delete30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClose_STORM_files.setIcon(icon22)
        self.actionClose_STORM_files.setObjectName("actionClose_STORM_files")
        self.actionClose_Confocal_files = QtWidgets.QAction(MainWindow)
        self.actionClose_Confocal_files.setIcon(icon22)
        self.actionClose_Confocal_files.setObjectName("actionClose_Confocal_files")
        self.actionSet_working_directory = QtWidgets.QAction(MainWindow)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/icon/icons/box11.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSet_working_directory.setIcon(icon23)
        self.actionSet_working_directory.setObjectName("actionSet_working_directory")
        self.actionPositioning_tool = QtWidgets.QAction(MainWindow)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/icon/icons/squares21.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPositioning_tool.setIcon(icon24)
        self.actionPositioning_tool.setObjectName("actionPositioning_tool")
        self.action_correlation_selecting = QtWidgets.QAction(MainWindow)
        self.action_correlation_selecting.setCheckable(True)
        self.action_correlation_selecting.setIcon(icon13)
        self.action_correlation_selecting.setObjectName("action_correlation_selecting")
        self.action_Roi_to_export = QtWidgets.QAction(MainWindow)
        self.action_Roi_to_export.setCheckable(False)
        self.action_Roi_to_export.setIcon(icon16)
        self.action_Roi_to_export.setObjectName("action_Roi_to_export")
        self.actionDragging_mode = QtWidgets.QAction(MainWindow)
        self.actionDragging_mode.setCheckable(True)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(":/icon/icons/arrow40.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDragging_mode.setIcon(icon25)
        self.actionDragging_mode.setObjectName("actionDragging_mode")
        self.actionCircle_ROI_selecting = QtWidgets.QAction(MainWindow)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(":/icon/icons/data68.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCircle_ROI_selecting.setIcon(icon26)
        self.actionCircle_ROI_selecting.setObjectName("actionCircle_ROI_selecting")
        self.actionImage_Registration = QtWidgets.QAction(MainWindow)
        self.actionImage_Registration.setIcon(icon24)
        self.actionImage_Registration.setObjectName("actionImage_Registration")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setIcon(icon21)
        self.actionExport.setObjectName("actionExport")
        self.toolBar_2.addAction(self.action_correlation_selecting)
        self.toolBar_2.addAction(self.action_Roi_to_export)
        self.toolBar_3.addAction(self.actionDragging_mode)
        self.toolBar_3.addAction(self.actionImage_Registration)
        self.toolBar_3.addAction(self.actionShow_1_m_scale)
        self.toolBar_3.addAction(self.actionLUT_changer)
        self.toolBar_3.addAction(self.action3D)
        self.toolBar_3.addAction(self.actionExport)

        self.retranslateUi(MainWindow)
        self.tabWidget_storm_tabs.setCurrentIndex(0)
        self.tabWidget_confocal_tabs.setCurrentIndex(0)
        self.comboBox_storm_channel1_color.setCurrentIndex(3)
        self.comboBox_storm_channel0_color.setCurrentIndex(4)
        self.comboBox_storm_channel2_color.setCurrentIndex(5)
        self.comboBox_storm_channel3_color.setCurrentIndex(0)
        self.comboBox_confocal_channel3_color.setCurrentIndex(3)
        self.comboBox_confocal_channel0_color.setCurrentIndex(0)
        self.comboBox_confocal_channel2_color.setCurrentIndex(2)
        self.comboBox_confocal_channel1_color.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CoSIdSTORM v 0.9"))
        self.groupBox_storm_top_controls.setTitle(_translate("MainWindow", "dSTORM images"))
        self.pushButton_open_storm.setText(_translate("MainWindow", "Open files..."))
        self.checkBox_trans_Matrix.setText(_translate("MainWindow", "Transform with matrix"))
        self.pushButton_close_all_storm.setText(_translate("MainWindow", "Close files"))
        self.pushButton_show_storm.setText(_translate("MainWindow", "Show selected"))
        self.pushButton_unload_storm.setText(_translate("MainWindow", "Unload selected"))
        self.pushButton_close_storm.setText(_translate("MainWindow", "Close selected"))
        self.tabWidget_storm_tabs.setTabText(self.tabWidget_storm_tabs.indexOf(self.tab), _translate("MainWindow", "Select"))
        self.groupBox_storm_config_fileheader.setTitle(_translate("MainWindow", "File header column numbers"))
        self.label_26.setText(_translate("MainWindow", "x"))
        self.label_28.setText(_translate("MainWindow", "y"))
        self.label_32.setText(_translate("MainWindow", "Frame"))
        self.label_29.setText(_translate("MainWindow", "Channel name"))
        self.label_31.setText(_translate("MainWindow", "Photon"))
        self.label_27.setText(_translate("MainWindow", "z"))
        self.label_30.setText(_translate("MainWindow", "Loc. accuracy"))
        self.groupBox_storm_config_display.setTitle(_translate("MainWindow", "Uniform dSTORM dot display"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-style:italic;\">d</span>STORM dot size (nm)</p></body></html>"))
        self.pushButton_apply_storm_config.setText(_translate("MainWindow", "Apply"))
        self.tabWidget_storm_tabs.setTabText(self.tabWidget_storm_tabs.indexOf(self.tab_2), _translate("MainWindow", "Config"))
        self.groupBox_storm_filter_z.setTitle(_translate("MainWindow", "Z filter"))
        self.label.setText(_translate("MainWindow", "From"))
        self.label_2.setText(_translate("MainWindow", "To"))
        self.groupBox_storm_filter_photon.setTitle(_translate("MainWindow", "Photon filter"))
        self.label_3.setText(_translate("MainWindow", "From"))
        self.label_7.setText(_translate("MainWindow", "To"))
        self.groupBox_storm_filter_frame.setTitle(_translate("MainWindow", "Frame filter"))
        self.label_9.setText(_translate("MainWindow", "From"))
        self.label_11.setText(_translate("MainWindow", "To"))
        self.groupBox_storm_filter_localdensity.setTitle(_translate("MainWindow", "Local density filter"))
        self.label_8.setText(_translate("MainWindow", "Radius [nm]"))
        self.label_10.setText(_translate("MainWindow", "Min number of neighbors"))
        self.pushButton_apply_storm_filters.setText(_translate("MainWindow", "Apply"))
        self.tabWidget_storm_tabs.setTabText(self.tabWidget_storm_tabs.indexOf(self.tab_6), _translate("MainWindow", "Filtering"))
        self.groupBox_confocal_top_controls.setTitle(_translate("MainWindow", "SIM images"))
        self.pushButton_open_confocal.setText(_translate("MainWindow", "Open files..."))
        self.checkBox_flip_lr.setText(_translate("MainWindow", "Flip left right"))
        self.checkBox_flip_ud.setText(_translate("MainWindow", "Flip top down"))
        self.pushButton_close_all_confocal.setText(_translate("MainWindow", "Close files"))
        self.pushButton_show_confocal.setText(_translate("MainWindow", "Show selected"))
        self.pushButton_unload_confocal.setText(_translate("MainWindow", "Unload selected"))
        self.pushButton_close_confocal.setText(_translate("MainWindow", "Close selected"))
        self.tabWidget_confocal_tabs.setTabText(self.tabWidget_confocal_tabs.indexOf(self.tab_3), _translate("MainWindow", "Select"))
        self.groupBox_confocal_config_resize_min_2.setTitle(_translate("MainWindow", "Resize interpolation min"))
        self.radioButton_confocal_config_min_nearest.setText(_translate("MainWindow", "Nearest neighbors"))
        self.radioButton_confocal_config_min_linear.setText(_translate("MainWindow", "Linear"))
        self.groupBox_confocal_config_resize_mag.setTitle(_translate("MainWindow", "Resize interpolation mag"))
        self.radioButton_confocal_config_mag_nearest.setText(_translate("MainWindow", "Nearest neighbors"))
        self.radioButton_confocal_config_mag_linear.setText(_translate("MainWindow", "Linear"))
        self.groupBox_confocal_config_calibration.setTitle(_translate("MainWindow", "Calibration"))
        self.label_4.setText(_translate("MainWindow", "Px [µm/pixel]"))
        self.pushButton_apply_confocal_config.setText(_translate("MainWindow", "Apply"))
        self.tabWidget_confocal_tabs.setTabText(self.tabWidget_confocal_tabs.indexOf(self.tab_4), _translate("MainWindow", "Config"))
        self.groupBox_confocal_display_appear.setTitle(_translate("MainWindow", "Appearance"))
        self.label_6.setText(_translate("MainWindow", "Transparency"))
        self.label_5.setText(_translate("MainWindow", "Z position"))
        self.groupBox_confocal_display_offset.setTitle(_translate("MainWindow", "Position offset (nm)"))
        self.label_12.setText(_translate("MainWindow", "x"))
        self.label_13.setText(_translate("MainWindow", "y"))
        self.pushButton_apply_confocal_display.setText(_translate("MainWindow", "Apply"))
        self.tabWidget_confocal_tabs.setTabText(self.tabWidget_confocal_tabs.indexOf(self.tab_5), _translate("MainWindow", "Display"))
        self.dockWidget.setWindowTitle(_translate("MainWindow", "3D Widget"))
        self.groupBox_storm_bottom_controls.setTitle(_translate("MainWindow", "dSTORM image"))
        self.checkBox_storm_channel1.setText(_translate("MainWindow", "Ch2"))
        self.checkBox_storm_channel3.setText(_translate("MainWindow", "Ch4"))
        self.checkBox_storm_channel0.setText(_translate("MainWindow", "Ch1"))
        self.checkBox_storm_channel2.setText(_translate("MainWindow", "Ch3"))
        self.comboBox_storm_channel1_color.setItemText(0, _translate("MainWindow", "red"))
        self.comboBox_storm_channel1_color.setItemText(1, _translate("MainWindow", "green"))
        self.comboBox_storm_channel1_color.setItemText(2, _translate("MainWindow", "blue"))
        self.comboBox_storm_channel1_color.setItemText(3, _translate("MainWindow", "cyan"))
        self.comboBox_storm_channel1_color.setItemText(4, _translate("MainWindow", "magenta"))
        self.comboBox_storm_channel1_color.setItemText(5, _translate("MainWindow", "yellow"))
        self.comboBox_storm_channel0_color.setItemText(0, _translate("MainWindow", "red"))
        self.comboBox_storm_channel0_color.setItemText(1, _translate("MainWindow", "green"))
        self.comboBox_storm_channel0_color.setItemText(2, _translate("MainWindow", "blue"))
        self.comboBox_storm_channel0_color.setItemText(3, _translate("MainWindow", "cyan"))
        self.comboBox_storm_channel0_color.setItemText(4, _translate("MainWindow", "magenta"))
        self.comboBox_storm_channel0_color.setItemText(5, _translate("MainWindow", "yellow"))
        self.comboBox_storm_channel2_color.setItemText(0, _translate("MainWindow", "red"))
        self.comboBox_storm_channel2_color.setItemText(1, _translate("MainWindow", "green"))
        self.comboBox_storm_channel2_color.setItemText(2, _translate("MainWindow", "blue"))
        self.comboBox_storm_channel2_color.setItemText(3, _translate("MainWindow", "cyan"))
        self.comboBox_storm_channel2_color.setItemText(4, _translate("MainWindow", "magenta"))
        self.comboBox_storm_channel2_color.setItemText(5, _translate("MainWindow", "yellow"))
        self.comboBox_storm_channel3_color.setItemText(0, _translate("MainWindow", "red"))
        self.comboBox_storm_channel3_color.setItemText(1, _translate("MainWindow", "green"))
        self.comboBox_storm_channel3_color.setItemText(2, _translate("MainWindow", "blue"))
        self.comboBox_storm_channel3_color.setItemText(3, _translate("MainWindow", "cyan"))
        self.comboBox_storm_channel3_color.setItemText(4, _translate("MainWindow", "magenta"))
        self.comboBox_storm_channel3_color.setItemText(5, _translate("MainWindow", "yellow"))
        self.label_storm_channel0_info.setText(_translate("MainWindow", "-"))
        self.label_storm_channel1_info.setText(_translate("MainWindow", "-"))
        self.label_storm_channel2_info.setText(_translate("MainWindow", "-"))
        self.label_storm_channel3_info.setText(_translate("MainWindow", "-"))
        self.groupBox_confocal_bottom_controls.setTitle(_translate("MainWindow", "SIM image"))
        self.comboBox_confocal_channel3_color.setItemText(0, _translate("MainWindow", "red"))
        self.comboBox_confocal_channel3_color.setItemText(1, _translate("MainWindow", "green"))
        self.comboBox_confocal_channel3_color.setItemText(2, _translate("MainWindow", "blue"))
        self.comboBox_confocal_channel3_color.setItemText(3, _translate("MainWindow", "cyan"))
        self.comboBox_confocal_channel3_color.setItemText(4, _translate("MainWindow", "magenta"))
        self.comboBox_confocal_channel3_color.setItemText(5, _translate("MainWindow", "yellow"))
        self.comboBox_confocal_channel0_color.setItemText(0, _translate("MainWindow", "red"))
        self.comboBox_confocal_channel0_color.setItemText(1, _translate("MainWindow", "green"))
        self.comboBox_confocal_channel0_color.setItemText(2, _translate("MainWindow", "blue"))
        self.comboBox_confocal_channel0_color.setItemText(3, _translate("MainWindow", "cyan"))
        self.comboBox_confocal_channel0_color.setItemText(4, _translate("MainWindow", "magenta"))
        self.comboBox_confocal_channel0_color.setItemText(5, _translate("MainWindow", "yellow"))
        self.comboBox_confocal_channel2_color.setItemText(0, _translate("MainWindow", "red"))
        self.comboBox_confocal_channel2_color.setItemText(1, _translate("MainWindow", "green"))
        self.comboBox_confocal_channel2_color.setItemText(2, _translate("MainWindow", "blue"))
        self.comboBox_confocal_channel2_color.setItemText(3, _translate("MainWindow", "cyan"))
        self.comboBox_confocal_channel2_color.setItemText(4, _translate("MainWindow", "magenta"))
        self.comboBox_confocal_channel2_color.setItemText(5, _translate("MainWindow", "yellow"))
        self.checkBox_confocal_channel0.setText(_translate("MainWindow", "Ch1"))
        self.checkBox_confocal_channel2.setText(_translate("MainWindow", "Ch3"))
        self.comboBox_confocal_channel1_color.setItemText(0, _translate("MainWindow", "red"))
        self.comboBox_confocal_channel1_color.setItemText(1, _translate("MainWindow", "green"))
        self.comboBox_confocal_channel1_color.setItemText(2, _translate("MainWindow", "blue"))
        self.comboBox_confocal_channel1_color.setItemText(3, _translate("MainWindow", "cyan"))
        self.comboBox_confocal_channel1_color.setItemText(4, _translate("MainWindow", "magenta"))
        self.comboBox_confocal_channel1_color.setItemText(5, _translate("MainWindow", "yellow"))
        self.label_confocal_info.setText(_translate("MainWindow", "-"))
        self.checkBox_confocal_channel1.setText(_translate("MainWindow", "Ch2"))
        self.checkBox_confocal_channel3.setText(_translate("MainWindow", "Ch4"))
        self.toolBar_2.setWindowTitle(_translate("MainWindow", "toolBar_2"))
        self.toolBar_3.setWindowTitle(_translate("MainWindow", "toolBar_3"))
        self.actionActiveContour_selector.setText(_translate("MainWindow", "Active contour selecting"))
        self.actionActiveContour_selector.setToolTip(_translate("MainWindow", "Active contour selecting (STORM)"))
        self.actionActiveContour_selector.setShortcut(_translate("MainWindow", "4"))
        self.actionLUT_changer.setText(_translate("MainWindow", "LUT settings"))
        self.actionLUT_changer.setToolTip(_translate("MainWindow", "LUT settings"))
        self.actionLUT_changer.setShortcut(_translate("MainWindow", "L"))
        self.action.setText(_translate("MainWindow", "Analysis runner"))
        self.action.setShortcut(_translate("MainWindow", "A"))
        self.actionVividSTORM_help.setText(_translate("MainWindow", "VividSTORM help"))
        self.actionVividSTORM_help.setShortcut(_translate("MainWindow", "F1"))
        self.actionAbout_VividSTORM.setText(_translate("MainWindow", "About VividSTORM"))
        self.actionAbout_VividSTORM.setShortcut(_translate("MainWindow", "F2"))
        self.actionDots.setText(_translate("MainWindow", "Dots view"))
        self.actionDots.setToolTip(_translate("MainWindow", "Dots view (STORM)"))
        self.actionGaussian.setText(_translate("MainWindow", "Gaussian view"))
        self.actionGaussian.setToolTip(_translate("MainWindow", "Gaussian view (STORM)"))
        self.action3D.setText(_translate("MainWindow", "3D view"))
        self.action3D.setToolTip(_translate("MainWindow", "3D view (STORM)"))
        self.action3D.setShortcut(_translate("MainWindow", "0"))
        self.actionShow_1_m_scale.setText(_translate("MainWindow", "Show  scale"))
        self.actionShow_1_m_scale.setShortcut(_translate("MainWindow", "S"))
        self.actionOpen_STORM_files.setText(_translate("MainWindow", "Open STORM files..."))
        self.actionOpen_STORM_files.setToolTip(_translate("MainWindow", "Open STORM image files"))
        self.actionOpen_STORM_files.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionOpen_Confocal_files.setText(_translate("MainWindow", "Open Confocal files..."))
        self.actionOpen_Confocal_files.setToolTip(_translate("MainWindow", "Open Confocal image files"))
        self.actionOpen_Confocal_files.setShortcut(_translate("MainWindow", "Ctrl+Shift+O"))
        self.actionExport_As_Image.setText(_translate("MainWindow", "Export as Image file..."))
        self.actionExport_As_Image.setIconText(_translate("MainWindow", "Export as image"))
        self.actionExport_As_Image.setToolTip(_translate("MainWindow", "Export as Image file"))
        self.actionClose_STORM_files.setText(_translate("MainWindow", "Close STORM files"))
        self.actionClose_STORM_files.setToolTip(_translate("MainWindow", "Close STORM files"))
        self.actionClose_STORM_files.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.actionClose_Confocal_files.setText(_translate("MainWindow", "Close Confocal files"))
        self.actionClose_Confocal_files.setToolTip(_translate("MainWindow", "Close Confocal files"))
        self.actionClose_Confocal_files.setShortcut(_translate("MainWindow", "Ctrl+Shift+X"))
        self.actionSet_working_directory.setText(_translate("MainWindow", "Set working directory..."))
        self.actionSet_working_directory.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.actionPositioning_tool.setText(_translate("MainWindow", "Positioning"))
        self.actionPositioning_tool.setToolTip(_translate("MainWindow", "Positioning tool (Confocal)"))
        self.action_correlation_selecting.setText(_translate("MainWindow", "Correlation ROI select"))
        self.action_correlation_selecting.setToolTip(_translate("MainWindow", "ROI select (Correlation)"))
        self.action_correlation_selecting.setShortcut(_translate("MainWindow", "1"))
        self.action_Roi_to_export.setText(_translate("MainWindow", "Roi to Export"))
        self.action_Roi_to_export.setToolTip(_translate("MainWindow", "Roi to Export"))
        self.action_Roi_to_export.setShortcut(_translate("MainWindow", "2"))
        self.actionDragging_mode.setText(_translate("MainWindow", "Dragging mode"))
        self.actionDragging_mode.setToolTip(_translate("MainWindow", "Dragging mode switch (Plot / Confocal)"))
        self.actionDragging_mode.setShortcut(_translate("MainWindow", "Space"))
        self.actionCircle_ROI_selecting.setText(_translate("MainWindow", "Circle ROI select"))
        self.actionCircle_ROI_selecting.setToolTip(_translate("MainWindow", "Circle ROI select (STORM)"))
        self.actionCircle_ROI_selecting.setShortcut(_translate("MainWindow", "3"))
        self.actionImage_Registration.setText(_translate("MainWindow", "Image Registration"))
        self.actionImage_Registration.setToolTip(_translate("MainWindow", "Register STORM and confocal images"))
        self.actionImage_Registration.setShortcut(_translate("MainWindow", "R"))
        self.actionExport.setText(_translate("MainWindow", "actionExport"))
        self.actionExport.setToolTip(_translate("MainWindow", "Export"))

from . import main_resources_rc
